"""BetDoc multi-sport bet engine."""
from app.schemas.bet_types import (
    NAMED_SYSTEM_BETS,
    AnyBetStructure,
    AnyLeg,
    AsianHandicapLeg,
    AsianOverUnderLeg,
    BaseLeg,
    BetStructure,
    BetStructureUnion,
    CalculatorResult,
    CanadianBet,
    CorrectScoreLeg,
    EachWayBet,
    EachWayLeg,
    ExposureResult,
    GoalscorerLeg,
    GoliathBet,
    HeinzBet,
    LayBet,
    LegSettlementContext,
    LegStatus,
    Lucky15Bet,
    Lucky31Bet,
    Lucky63Bet,
    MarketType,
    NamedSystemBet,
    ParlayBet,
    PatentBet,
    PlayerPropLeg,
    SettleRequest,
    SettlementResult,
    SimpleLeg,
    SingleBet,
    SuperHeinzBet,
    SystemBet,
    SystemBetBase,
    TrixieBet,
    YankeeBet,
)
from app.domain.bet_types.calculator import (
    calculate_potential_return,
    calculate_total_stake,
    line_stake,
    number_of_bets,
    structure_combinations,
    structure_fold_sizes,
    summarize_structure,
)
from app.domain.bet_types.exposure import build_exposure_result, calculate_bet_exposure
from app.domain.bet_types.resolvers import (
    settle_asian_handicap,
    settle_asian_total,
    settle_correct_score,
    settle_player_prop,
    split_asian_line,
)
from app.domain.bet_types.settler import (
    SettlementError,
    effective_place_odds,
    effective_win_odds,
    resolved_status,
    settle_bet,
)

__all__ = [
    "MarketType", "LegStatus", "BaseLeg", "SimpleLeg", "AsianHandicapLeg", "AsianOverUnderLeg",
    "CorrectScoreLeg", "GoalscorerLeg", "PlayerPropLeg", "EachWayLeg", "AnyLeg",
    "LegSettlementContext", "CalculatorResult", "SettlementResult", "ExposureResult",
    "BetStructure", "SingleBet", "ParlayBet", "SystemBetBase", "SystemBet", "NamedSystemBet",
    "TrixieBet", "PatentBet", "YankeeBet", "Lucky15Bet", "CanadianBet", "Lucky31Bet",
    "HeinzBet", "Lucky63Bet", "SuperHeinzBet", "GoliathBet", "EachWayBet", "LayBet",
    "AnyBetStructure", "BetStructureUnion", "NAMED_SYSTEM_BETS", "SettleRequest",
    "structure_combinations", "structure_fold_sizes", "line_stake", "number_of_bets",
    "calculate_potential_return", "calculate_total_stake", "summarize_structure",
    "calculate_bet_exposure", "build_exposure_result",
    "split_asian_line", "settle_asian_handicap", "settle_asian_total",
    "settle_player_prop", "settle_correct_score",
    "effective_win_odds", "effective_place_odds", "resolved_status", "settle_bet", "SettlementError",
]
