"""initial

Revision ID: 3601079cbd79
Revises: 
Create Date: 2026-09-07 10:51:14.647361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import adapters
revision: str = '3601079cbd79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('market_key', sa.String(length=128), nullable=False),
    sa.Column('outcome_key', sa.String(length=64), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('stake_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'won', 'lost', 'void', 'half_won', 'half_lost', name='bet_status', native_enum=False), nullable=False),
    sa.Column('placed_at', adapters.persistence.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('settled_at', adapters.persistence.models.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'pending' AND settled_at IS NULL) OR (status <> 'pending' AND settled_at IS NOT NULL)", name='ck_bet_records_settlement_coherent'),
    sa.CheckConstraint('odds > 1.0', name='ck_bet_records_odds_above_one'),
    sa.CheckConstraint('stake_paise > 0', name='ck_bet_records_stake_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bet_records_bookmaker_placed_at', 'bet_records', ['bookmaker', 'placed_at'], unique=False)
    op.create_index('ix_bet_records_event', 'bet_records', ['event_id', 'market_key', 'outcome_key'], unique=False)
    op.create_index('ix_bet_records_status_placed_at', 'bet_records', ['status', 'placed_at'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='account_type', native_enum=False), nullable=False),
    sa.Column('created_at', adapters.persistence.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_ledger_accounts_type', 'ledger_accounts', ['account_type'], unique=False)
    op.create_table('odds_ticks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', adapters.persistence.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('market_key', sa.String(length=128), nullable=False),
    sa.Column('outcome_key', sa.String(length=64), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.CheckConstraint('decimal_odds > 1.0', name='ck_odds_ticks_odds_above_one'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='pk_odds_ticks'),
    sa.UniqueConstraint('bookmaker', 'event_id', 'market_key', 'outcome_key', 'timestamp', name='uq_odds_ticks_natural_key')
    )
    op.create_index('ix_odds_ticks_bookmaker_timestamp', 'odds_ticks', ['bookmaker', 'timestamp'], unique=False)
    op.create_index('ix_odds_ticks_lookup', 'odds_ticks', ['event_id', 'market_key', 'outcome_key', 'timestamp'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', adapters.persistence.models.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_paise <> 0', name='ck_ledger_entries_amount_nonzero'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index('ix_ledger_entries_account_timestamp', 'ledger_entries', ['account_id', 'timestamp'], unique=False)
    op.create_index('ix_ledger_entries_transaction', 'ledger_entries', ['transaction_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    
    # TimescaleDB hypertable for high-frequency odds time-series
    op.execute("SELECT create_hypertable('odds_ticks', 'timestamp');")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_transaction', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_timestamp', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_odds_ticks_lookup', table_name='odds_ticks')
    op.drop_index('ix_odds_ticks_bookmaker_timestamp', table_name='odds_ticks')
    op.drop_table('odds_ticks')
    op.drop_index('ix_ledger_accounts_type', table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index('ix_bet_records_status_placed_at', table_name='bet_records')
    op.drop_index('ix_bet_records_event', table_name='bet_records')
    op.drop_index('ix_bet_records_bookmaker_placed_at', table_name='bet_records')
    op.drop_table('bet_records')
    # ### end Alembic commands ###
