"""sentinel alerting channels and trail

Revision ID: 02835599ce32
Revises: 5e4e1106d21a
Create Date: 2026-10-09 18:05:56.528779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02835599ce32'
down_revision: Union[str, Sequence[str], None] = '5e4e1106d21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentinel_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_id', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentinel_alerts'))
    )
    op.create_index('ix_sentinel_alerts_kind_occurred_at', 'sentinel_alerts', ['kind', 'occurred_at'], unique=False)
    op.create_index('ix_sentinel_alerts_occurred_at', 'sentinel_alerts', ['occurred_at'], unique=False)
    op.create_table('sentinel_channels',
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('credentials_hint', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('channel', name=op.f('pk_sentinel_channels'))
    )
    op.create_table('sentinel_commands',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('authorised', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentinel_commands'))
    )
    op.create_index('ix_sentinel_commands_received_at', 'sentinel_commands', ['received_at'], unique=False)
    op.create_table('sentinel_deliveries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('digest_id', sa.Uuid(), nullable=True),
    sa.Column('batched', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentinel_deliveries'))
    )
    op.create_index('ix_sentinel_deliveries_alert_id', 'sentinel_deliveries', ['alert_id'], unique=False)
    op.create_index('ix_sentinel_deliveries_attempted_at', 'sentinel_deliveries', ['attempted_at'], unique=False)
    op.create_table('sentinel_routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_sentinel_routing_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentinel_routing'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentinel_routing')
    op.drop_index('ix_sentinel_deliveries_attempted_at', table_name='sentinel_deliveries')
    op.drop_index('ix_sentinel_deliveries_alert_id', table_name='sentinel_deliveries')
    op.drop_table('sentinel_deliveries')
    op.drop_index('ix_sentinel_commands_received_at', table_name='sentinel_commands')
    op.drop_table('sentinel_commands')
    op.drop_table('sentinel_channels')
    op.drop_index('ix_sentinel_alerts_occurred_at', table_name='sentinel_alerts')
    op.drop_index('ix_sentinel_alerts_kind_occurred_at', table_name='sentinel_alerts')
    op.drop_table('sentinel_alerts')
    # ### end Alembic commands ###
