"""added exchange account constraint

Revision ID: 0b0e29629b28
Revises: 5341a002ae8a
Create Date: 2026-09-26 20:06:46.234123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0e29629b28'
down_revision: Union[str, Sequence[str], None] = '5341a002ae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_exchange', 'exchange_accounts', ['user_id', 'exchange_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_exchange', 'exchange_accounts', type_='unique')
    # ### end Alembic commands ###
