"""sniper execution venues

Group 63: execution venues (a bookmaker's order API, its auth and its outbound rate) and the
canonical -> bookmaker id mappings. The bet ledger gains the bookmaker's remote_bet_id (renamed
from bookmaker_ref), the order resolver's retry bookkeeping and a dead-letter status
(REQUIRES_MANUAL_INTERVENTION); risk settings gain the slippage tolerance.

Revision ID: 180f198651da
Revises: 41d7b45c6684
Create Date: 2026-10-08 21:00:44.842717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

WIDENED = (("cfo_audit_log", "event"), ("cfo_ledger_entries", "kind"), ("cfo_ledger_entries", "account"), ("cfo_phantom_ledger", "status"))
STATUSES = ("PENDING", "WON", "LOST", "REJECTED", "VOID", "REQUIRES_MANUAL_INTERVENTION")
AUDIT_EVENTS = ("EXECUTION_ATTEMPT", "EXECUTED", "BLOCKED", "BOOKMAKER_REJECTED", "EXECUTION_UNKNOWN", "COMMIT_FAILED", "SETTLED", "DEAD_LETTERED")
SETTLEMENT_CONSISTENT = (
    "(status IN ('PENDING', 'REQUIRES_MANUAL_INTERVENTION') AND settled_at IS NULL)"
    " OR (status NOT IN ('PENDING', 'REQUIRES_MANUAL_INTERVENTION') AND settled_at IS NOT NULL)"
)
OLD_SETTLEMENT_CONSISTENT = "(status = 'PENDING' AND settled_at IS NULL) OR (status <> 'PENDING' AND settled_at IS NOT NULL)"


def _in(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{v}'" for v in values)

# revision identifiers, used by Alembic.
revision: str = '180f198651da'
down_revision: Union[str, Sequence[str], None] = '41d7b45c6684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sniper_execution_venues',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('token_path', sa.String(length=128), nullable=True),
    sa.Column('refresh_path', sa.String(length=128), nullable=True),
    sa.Column('place_path', sa.String(length=128), nullable=False),
    sa.Column('status_path', sa.String(length=128), nullable=False),
    sa.Column('events_path', sa.String(length=128), nullable=True),
    sa.Column('bets_per_second', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('burst', sa.Integer(), nullable=False),
    sa.Column('routes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('selection_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('credentials_hint', sa.String(length=64), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("adapter IN ('generic_json')", name=op.f('ck_sniper_execution_venues_adapter_valid')),
    sa.CheckConstraint("auth_type IN ('oauth2_client_credentials', 'static_bearer')", name=op.f('ck_sniper_execution_venues_auth_type_valid')),
    sa.CheckConstraint('bets_per_second > 0 AND bets_per_second <= 50', name=op.f('ck_sniper_execution_venues_rate_range')),
    sa.CheckConstraint('burst >= 1 AND burst <= 50', name=op.f('ck_sniper_execution_venues_burst_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sniper_execution_venues'))
    )
    op.create_table('sniper_entity_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('canonical_key', sa.String(length=256), nullable=False),
    sa.Column('remote_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('fixture', 'selection')", name=op.f('ck_sniper_entity_mappings_kind_valid')),
    sa.CheckConstraint('length(remote_id) > 0', name=op.f('ck_sniper_entity_mappings_remote_id_not_empty')),
    sa.ForeignKeyConstraint(['venue_id'], ['sniper_execution_venues.id'], name=op.f('fk_sniper_entity_mappings_venue_id_sniper_execution_venues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sniper_entity_mappings')),
    sa.UniqueConstraint('venue_id', 'kind', 'canonical_key', name='uq_sniper_entity_mappings_key')
    )
    op.create_index('ix_sniper_entity_mappings_venue_remote', 'sniper_entity_mappings', ['venue_id', 'kind', 'remote_id'], unique=False)
    # Enum columns widen to 32 characters (REQUIRES_MANUAL_INTERVENTION is 28)
    for table, column in WIDENED:
        op.alter_column(table, column, existing_type=sa.VARCHAR(length=24), type_=sa.String(length=32), existing_nullable=False)
    op.drop_constraint(op.f("ck_cfo_phantom_ledger_cfo_ledger_status"), "cfo_phantom_ledger", type_="check")
    op.create_check_constraint("cfo_ledger_status", "cfo_phantom_ledger", f"status IN ({_in(STATUSES)})")
    op.drop_constraint(op.f("ck_cfo_phantom_ledger_settlement_consistent"), "cfo_phantom_ledger", type_="check")
    op.create_check_constraint("settlement_consistent", "cfo_phantom_ledger", SETTLEMENT_CONSISTENT)
    op.drop_constraint(op.f("ck_cfo_audit_log_cfo_audit_event"), "cfo_audit_log", type_="check")
    op.create_check_constraint("cfo_audit_event", "cfo_audit_log", f"event IN ({_in(AUDIT_EVENTS)})")

    # The bookmaker's own bet id (renamed: no data is dropped) and the order resolver's bookkeeping
    op.alter_column("cfo_phantom_ledger", "bookmaker_ref", new_column_name="remote_bet_id")
    op.add_column("cfo_phantom_ledger", sa.Column("commence_time", sa.DateTime(timezone=True), nullable=True))
    op.add_column("cfo_phantom_ledger", sa.Column("resolve_attempts", sa.Integer(), server_default="0", nullable=False))
    op.add_column("cfo_phantom_ledger", sa.Column("next_resolve_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("cfo_phantom_ledger", sa.Column("last_resolve_error", sa.String(length=255), nullable=True))
    op.create_check_constraint("resolve_attempts_non_negative", "cfo_phantom_ledger", "resolve_attempts >= 0")
    op.create_index("ix_cfo_phantom_ledger_status_next_resolve", "cfo_phantom_ledger", ["status", "next_resolve_at"], unique=False)

    op.add_column("cfo_risk_settings", sa.Column("max_slippage_pct", sa.Numeric(precision=5, scale=2), server_default="0.50", nullable=False))
    op.create_check_constraint("slippage_range", "cfo_risk_settings", "max_slippage_pct >= 0 AND max_slippage_pct <= 5")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_cfo_risk_settings_slippage_range"), "cfo_risk_settings", type_="check")
    op.drop_column("cfo_risk_settings", "max_slippage_pct")
    op.drop_index("ix_cfo_phantom_ledger_status_next_resolve", table_name="cfo_phantom_ledger")
    op.drop_constraint(op.f("ck_cfo_phantom_ledger_resolve_attempts_non_negative"), "cfo_phantom_ledger", type_="check")
    op.drop_column("cfo_phantom_ledger", "last_resolve_error")
    op.drop_column("cfo_phantom_ledger", "next_resolve_at")
    op.drop_column("cfo_phantom_ledger", "resolve_attempts")
    op.drop_column("cfo_phantom_ledger", "commence_time")
    op.alter_column("cfo_phantom_ledger", "remote_bet_id", new_column_name="bookmaker_ref")

    # Dead-lettered bets go back to PENDING (their stake is still in exposure, which PENDING means too)
    op.execute("UPDATE cfo_phantom_ledger SET status = 'PENDING' WHERE status = 'REQUIRES_MANUAL_INTERVENTION'")
    op.drop_constraint(op.f("ck_cfo_phantom_ledger_settlement_consistent"), "cfo_phantom_ledger", type_="check")
    op.create_check_constraint("settlement_consistent", "cfo_phantom_ledger", OLD_SETTLEMENT_CONSISTENT)
    op.drop_constraint(op.f("ck_cfo_phantom_ledger_cfo_ledger_status"), "cfo_phantom_ledger", type_="check")
    op.create_check_constraint("cfo_ledger_status", "cfo_phantom_ledger", f"status IN ({_in(STATUSES[:-1])})")
    # The audit log is append-only: DEAD_LETTERED rows stay, so the old check skips existing rows
    op.drop_constraint(op.f("ck_cfo_audit_log_cfo_audit_event"), "cfo_audit_log", type_="check")
    op.execute(f"ALTER TABLE cfo_audit_log ADD CONSTRAINT ck_cfo_audit_log_cfo_audit_event CHECK (event IN ({_in(AUDIT_EVENTS[:-1])})) NOT VALID")
    for table, column in WIDENED:  # every remaining value fits 24 characters again
        op.alter_column(table, column, existing_type=sa.String(length=32), type_=sa.VARCHAR(length=24), existing_nullable=False)

    op.drop_index("ix_sniper_entity_mappings_venue_remote", table_name="sniper_entity_mappings")
    op.drop_table("sniper_entity_mappings")
    op.drop_table("sniper_execution_venues")
