"""Group 40: The Lab

Revision ID: 1a373103a51e
Revises: 9b10c512d78a
Create Date: 2026-09-29 15:18:18.243370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a373103a51e'
down_revision: Union[str, Sequence[str], None] = '9b10c512d78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('model_a_name', sa.String(length=100), nullable=False),
    sa.Column('model_b_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'CONCLUDED')", name=op.f('ck_lab_experiments_ck_lab_experiments_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_experiments'))
    )
    op.create_index(op.f('ix_lab_experiments_created_at'), 'lab_experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_experiments_name'), 'lab_experiments', ['name'], unique=False)
    op.create_index(op.f('ix_lab_experiments_status'), 'lab_experiments', ['status'], unique=False)
    op.create_table('lab_research_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')", name=op.f('ck_lab_research_reports_ck_lab_research_reports_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_research_reports'))
    )
    op.create_index(op.f('ix_lab_research_reports_category'), 'lab_research_reports', ['category'], unique=False)
    op.create_index(op.f('ix_lab_research_reports_created_at'), 'lab_research_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_research_reports_status'), 'lab_research_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_research_reports_status'), table_name='lab_research_reports')
    op.drop_index(op.f('ix_lab_research_reports_created_at'), table_name='lab_research_reports')
    op.drop_index(op.f('ix_lab_research_reports_category'), table_name='lab_research_reports')
    op.drop_table('lab_research_reports')
    op.drop_index(op.f('ix_lab_experiments_status'), table_name='lab_experiments')
    op.drop_index(op.f('ix_lab_experiments_name'), table_name='lab_experiments')
    op.drop_index(op.f('ix_lab_experiments_created_at'), table_name='lab_experiments')
    op.drop_table('lab_experiments')
    # ### end Alembic commands ###
