"""Add odds_snapshots table

Revision ID: 2761cd64aae9
Revises: 0b0e29629b28
Create Date: 2026-09-27 12:46:10.780114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2761cd64aae9'
down_revision: Union[str, Sequence[str], None] = '0b0e29629b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('sport_key', sa.String(), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bookmaker_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots'))
    )
    op.create_index('ix_match_bookmaker_time', 'odds_snapshots', ['match_id', 'bookmaker', 'timestamp'], unique=False)
    op.create_index('ix_sport_time', 'odds_snapshots', ['sport_key', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sport_time', table_name='odds_snapshots')
    op.drop_index('ix_match_bookmaker_time', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    # ### end Alembic commands ###
