"""cfo vault ledger

Group 62: the CFO cash ledger. Per-user bankroll accounts (locked on every money movement), the
double-entry journal behind their balances, the bet ledger, an append-only audit log, per-user risk
guard settings and graded market results. The journal and the audit log get a trigger that refuses
UPDATE and DELETE.

Revision ID: 41d7b45c6684
Revises: 7b3e91c4d2a8
Create Date: 2026-10-08 20:22:34.998345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Frozen here (not imported from the app) so this revision never changes under a later refactor
APPEND_ONLY_TABLES = ("cfo_audit_log", "cfo_ledger_entries")
APPEND_ONLY_FUNCTION = """
CREATE OR REPLACE FUNCTION cfo_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only (% blocked)', TG_TABLE_NAME, TG_OP;
END;
$$;
"""


def append_only_trigger(table: str) -> str:
    return f"CREATE TRIGGER trg_{table}_append_only BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION cfo_append_only();"

# revision identifiers, used by Alembic.
revision: str = '41d7b45c6684'
down_revision: Union[str, Sequence[str], None] = '7b3e91c4d2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfo_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.Enum('EXECUTION_ATTEMPT', 'EXECUTED', 'BLOCKED', 'BOOKMAKER_REJECTED', 'EXECUTION_UNKNOWN', 'COMMIT_FAILED', 'SETTLED', name='cfo_audit_event', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=True),
    sa.Column('ledger_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.String(length=128), nullable=True),
    sa.Column('selection', sa.String(length=64), nullable=True),
    sa.Column('stake_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pnl_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_audit_log'))
    )
    op.create_index('ix_cfo_audit_log_user_created', 'cfo_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_cfo_audit_log_user_event_created', 'cfo_audit_log', ['user_id', 'event', 'created_at'], unique=False)
    op.create_table('cfo_market_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('winning_selection', sa.String(length=64), nullable=True),
    sa.Column('is_void', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_void AND winning_selection IS NULL) OR (NOT is_void AND winning_selection IS NOT NULL)', name=op.f('ck_cfo_market_results_outcome_consistent')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_market_results')),
    sa.UniqueConstraint('fixture_id', 'market', name='uq_cfo_market_results_fixture_market')
    )
    op.create_table('cfo_bankroll_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exposure_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('peak_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('postings', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_balance >= 0', name=op.f('ck_cfo_bankroll_accounts_available_non_negative')),
    sa.CheckConstraint('exposure_balance >= 0', name=op.f('ck_cfo_bankroll_accounts_exposure_non_negative')),
    sa.CheckConstraint('peak_balance >= 0', name=op.f('ck_cfo_bankroll_accounts_peak_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cfo_bankroll_accounts_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_bankroll_accounts')),
    sa.UniqueConstraint('user_id', name=op.f('uq_cfo_bankroll_accounts_user_id'))
    )
    op.create_table('cfo_phantom_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=64), nullable=False),
    sa.Column('bookmaker_ref', sa.String(length=128), nullable=True),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('stake_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('true_prob', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('potential_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'REJECTED', 'VOID', name='cfo_ledger_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('reconcile_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'PENDING' AND settled_at IS NULL) OR (status <> 'PENDING' AND settled_at IS NOT NULL)", name=op.f('ck_cfo_phantom_ledger_settlement_consistent')),
    sa.CheckConstraint('odds > 1', name=op.f('ck_cfo_phantom_ledger_odds_above_one')),
    sa.CheckConstraint('potential_pnl >= 0', name=op.f('ck_cfo_phantom_ledger_potential_pnl_non_negative')),
    sa.CheckConstraint('stake_inr > 0', name=op.f('ck_cfo_phantom_ledger_stake_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cfo_phantom_ledger_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_phantom_ledger')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_cfo_phantom_ledger_user_idempotency')
    )
    op.create_index('ix_cfo_phantom_ledger_fixture_market_status', 'cfo_phantom_ledger', ['fixture_id', 'market', 'status'], unique=False)
    op.create_index('ix_cfo_phantom_ledger_user_fixture_status', 'cfo_phantom_ledger', ['user_id', 'fixture_id', 'status'], unique=False)
    op.create_index('ix_cfo_phantom_ledger_user_status', 'cfo_phantom_ledger', ['user_id', 'status'], unique=False)
    op.create_table('cfo_risk_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('daily_drawdown_pct', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False),
    sa.Column('max_market_exposure_pct', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False),
    sa.Column('max_loss_streak', sa.Integer(), server_default='5', nullable=False),
    sa.Column('velocity_max_cv_pct', sa.Numeric(precision=5, scale=2), server_default='3.00', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('daily_drawdown_pct >= 1 AND daily_drawdown_pct <= 50', name=op.f('ck_cfo_risk_settings_drawdown_range')),
    sa.CheckConstraint('max_loss_streak >= 1 AND max_loss_streak <= 20', name=op.f('ck_cfo_risk_settings_loss_streak_range')),
    sa.CheckConstraint('max_market_exposure_pct >= 1 AND max_market_exposure_pct <= 50', name=op.f('ck_cfo_risk_settings_market_exposure_range')),
    sa.CheckConstraint('velocity_max_cv_pct >= 0.5 AND velocity_max_cv_pct <= 20', name=op.f('ck_cfo_risk_settings_velocity_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cfo_risk_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_cfo_risk_settings'))
    )
    op.create_table('cfo_ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('OPEN', 'RESERVE', 'RELEASE', 'SETTLE_WON', 'SETTLE_LOST', name='cfo_posting_kind', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('account', sa.Enum('AVAILABLE', 'EXPOSURE', 'PNL', 'EQUITY', name='cfo_ledger_account', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_cfo_ledger_entries_amount_non_zero')),
    sa.ForeignKeyConstraint(['ledger_id'], ['cfo_phantom_ledger.id'], name=op.f('fk_cfo_ledger_entries_ledger_id_cfo_phantom_ledger'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cfo_ledger_entries_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_ledger_entries'))
    )
    op.create_index('ix_cfo_ledger_entries_journal', 'cfo_ledger_entries', ['journal_id'], unique=False)
    op.create_index('ix_cfo_ledger_entries_user_account', 'cfo_ledger_entries', ['user_id', 'account'], unique=False)
    # ### end Alembic commands ###
    op.execute(APPEND_ONLY_FUNCTION)
    for table in APPEND_ONLY_TABLES:
        op.execute(append_only_trigger(table))


def downgrade() -> None:
    """Downgrade schema."""
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS cfo_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cfo_ledger_entries_user_account', table_name='cfo_ledger_entries')
    op.drop_index('ix_cfo_ledger_entries_journal', table_name='cfo_ledger_entries')
    op.drop_table('cfo_ledger_entries')
    op.drop_table('cfo_risk_settings')
    op.drop_index('ix_cfo_phantom_ledger_user_status', table_name='cfo_phantom_ledger')
    op.drop_index('ix_cfo_phantom_ledger_user_fixture_status', table_name='cfo_phantom_ledger')
    op.drop_index('ix_cfo_phantom_ledger_fixture_market_status', table_name='cfo_phantom_ledger')
    op.drop_table('cfo_phantom_ledger')
    op.drop_table('cfo_bankroll_accounts')
    op.drop_table('cfo_market_results')
    op.drop_index('ix_cfo_audit_log_user_event_created', table_name='cfo_audit_log')
    op.drop_index('ix_cfo_audit_log_user_created', table_name='cfo_audit_log')
    op.drop_table('cfo_audit_log')
    # ### end Alembic commands ###
