"""lab backtesting history and commission rates

Group 66. The Lab's point-in-time market history (lab_hist_fixtures, lab_hist_ticks,
lab_hist_results, lab_hist_fx_rates) and its backtest runs (lab_backtest_runs). The commission gap:
cfo_phantom_ledger.commission_rate and hive_shadow_positions.commission_rate record the venue's cut
of net winnings each bet was booked net of (0 for every existing row: they were booked gross).

Revision ID: 4d1e44adf936
Revises: 9c83ee5f76f2
Create Date: 2026-10-09 13:19:46.412847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d1e44adf936'
down_revision: Union[str, Sequence[str], None] = '9c83ee5f76f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_hist_fixtures',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('sport_key', sa.String(length=64), nullable=False),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_hist_fixtures'))
    )
    op.create_index('ix_lab_hist_fixtures_commence_time', 'lab_hist_fixtures', ['commence_time'], unique=False)
    op.create_table('lab_hist_fx_rates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('inr_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('inr_per_unit > 0', name=op.f('ck_lab_hist_fx_rates_rate_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_hist_fx_rates')),
    sa.UniqueConstraint('currency', 'created_at', name='uq_lab_hist_fx_rates_currency_time')
    )
    op.create_index('ix_lab_hist_fx_rates_lookup', 'lab_hist_fx_rates', ['currency', 'created_at'], unique=False)
    op.create_table('lab_backtest_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')", name=op.f('ck_lab_backtest_runs_status_known')),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name=op.f('ck_lab_backtest_runs_progress_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lab_backtest_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_backtest_runs'))
    )
    op.create_index('ix_lab_backtest_runs_user_created', 'lab_backtest_runs', ['user_id', 'created_at'], unique=False)
    op.create_table('lab_hist_results',
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'FINISHED' AND home_goals >= 0 AND away_goals >= 0) OR (status = 'POSTPONED' AND home_goals IS NULL AND away_goals IS NULL)", name=op.f('ck_lab_hist_results_score_consistent')),
    sa.CheckConstraint("status IN ('FINISHED', 'POSTPONED')", name=op.f('ck_lab_hist_results_status_known')),
    sa.ForeignKeyConstraint(['fixture_id'], ['lab_hist_fixtures.id'], name=op.f('fk_lab_hist_results_fixture_id_lab_hist_fixtures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fixture_id', name=op.f('pk_lab_hist_results'))
    )
    op.create_index('ix_lab_hist_results_created_at', 'lab_hist_results', ['created_at'], unique=False)
    op.create_table('lab_hist_ticks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=64), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('liquidity IS NULL OR liquidity >= 0', name=op.f('ck_lab_hist_ticks_liquidity_non_negative')),
    sa.CheckConstraint('odds > 1', name=op.f('ck_lab_hist_ticks_odds_above_one')),
    sa.ForeignKeyConstraint(['fixture_id'], ['lab_hist_fixtures.id'], name=op.f('fk_lab_hist_ticks_fixture_id_lab_hist_fixtures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_hist_ticks'))
    )
    op.create_index('ix_lab_hist_ticks_created_at', 'lab_hist_ticks', ['created_at'], unique=False)
    op.create_index('ix_lab_hist_ticks_market_time', 'lab_hist_ticks', ['fixture_id', 'market', 'created_at'], unique=False)
    op.add_column('cfo_phantom_ledger', sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False))
    op.add_column('hive_shadow_positions', sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False))
    op.create_check_constraint('commission_rate_range', 'cfo_phantom_ledger', 'commission_rate >= 0 AND commission_rate < 0.5')
    op.create_check_constraint('commission_rate_range', 'hive_shadow_positions', 'commission_rate >= 0 AND commission_rate < 0.5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_hive_shadow_positions_commission_rate_range'), 'hive_shadow_positions', type_='check')
    op.drop_constraint(op.f('ck_cfo_phantom_ledger_commission_rate_range'), 'cfo_phantom_ledger', type_='check')
    op.drop_column('hive_shadow_positions', 'commission_rate')
    op.drop_column('cfo_phantom_ledger', 'commission_rate')
    op.drop_index('ix_lab_hist_ticks_market_time', table_name='lab_hist_ticks')
    op.drop_index('ix_lab_hist_ticks_created_at', table_name='lab_hist_ticks')
    op.drop_table('lab_hist_ticks')
    op.drop_index('ix_lab_hist_results_created_at', table_name='lab_hist_results')
    op.drop_table('lab_hist_results')
    op.drop_index('ix_lab_backtest_runs_user_created', table_name='lab_backtest_runs')
    op.drop_table('lab_backtest_runs')
    op.drop_index('ix_lab_hist_fx_rates_lookup', table_name='lab_hist_fx_rates')
    op.drop_table('lab_hist_fx_rates')
    op.drop_index('ix_lab_hist_fixtures_commence_time', table_name='lab_hist_fixtures')
    op.drop_table('lab_hist_fixtures')
    # ### end Alembic commands ###
