"""initial

Revision ID: 5341a002ae8a
Revises: 
Create Date: 2026-09-26 13:01:33.922025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5341a002ae8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='QUANT', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exchange_name', sa.String(length=64), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=False),
    sa.Column('api_secret_encrypted', sa.String(), nullable=False),
    sa.Column('key_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exchange_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_accounts'))
    )
    op.create_index(op.f('ix_exchange_accounts_user_id'), 'exchange_accounts', ['user_id'], unique=False)
    op.create_table('risk_mandates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('max_stake_per_bet', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('max_daily_exposure', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('kill_threshold_pct', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.CheckConstraint('kill_threshold_pct >= 0 AND kill_threshold_pct <= 100', name=op.f('ck_risk_mandates_kill_threshold_range')),
    sa.CheckConstraint('max_daily_exposure > 0', name=op.f('ck_risk_mandates_max_exposure_positive')),
    sa.CheckConstraint('max_stake_per_bet <= max_daily_exposure', name=op.f('ck_risk_mandates_stake_within_exposure')),
    sa.CheckConstraint('max_stake_per_bet > 0', name=op.f('ck_risk_mandates_max_stake_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_mandates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_mandates')),
    sa.UniqueConstraint('user_id', name=op.f('uq_risk_mandates_user_id'))
    )
    op.create_table('bet_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('exchange_account_id', sa.Uuid(), nullable=False),
    sa.Column('exchange_bet_id', sa.String(length=128), nullable=True),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('odds', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('stake', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('payout', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('true_probability', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status IN ('PENDING', 'PENDING_NETWORK', 'UNKNOWN', 'ACCEPTED') AND resolved_at IS NULL AND payout IS NULL) OR (status IN ('WON', 'LOST', 'VOID', 'REJECTED') AND resolved_at IS NOT NULL)", name=op.f('ck_bet_ledger_resolution_consistent')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_bet_ledger_currency_iso4217')),
    sa.CheckConstraint("status IN ('PENDING', 'PENDING_NETWORK', 'ACCEPTED', 'REJECTED', 'UNKNOWN', 'WON', 'LOST', 'VOID')", name=op.f('ck_bet_ledger_status_valid')),
    sa.CheckConstraint('odds > 1', name=op.f('ck_bet_ledger_odds_above_one')),
    sa.CheckConstraint('payout IS NULL OR payout >= 0', name=op.f('ck_bet_ledger_payout_non_negative')),
    sa.CheckConstraint('stake > 0', name=op.f('ck_bet_ledger_stake_positive')),
    sa.CheckConstraint('true_probability >= 0 AND true_probability <= 1', name=op.f('ck_bet_ledger_true_probability_range')),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], name=op.f('fk_bet_ledger_exchange_account_id_exchange_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bet_ledger')),
    sa.UniqueConstraint('exchange_account_id', 'exchange_bet_id', name='uq_bet_ledger_account_exchange_bet')
    )
    op.create_index('ix_bet_ledger_account_placed_at', 'bet_ledger', ['exchange_account_id', 'placed_at'], unique=False)
    op.create_index('ix_bet_ledger_account_status', 'bet_ledger', ['exchange_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_bet_ledger_exchange_bet_id'), 'bet_ledger', ['exchange_bet_id'], unique=False)
    op.create_index(op.f('ix_bet_ledger_idempotency_key'), 'bet_ledger', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bet_ledger_match_id'), 'bet_ledger', ['match_id'], unique=False)
    op.create_index(op.f('ix_bet_ledger_status'), 'bet_ledger', ['status'], unique=False)
    op.create_index('ix_bet_ledger_sweep_pending', 'bet_ledger', ['status', 'placed_at'], unique=False, postgresql_where=sa.text("status = 'PENDING_NETWORK'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bet_ledger_sweep_pending', table_name='bet_ledger', postgresql_where=sa.text("status = 'PENDING_NETWORK'"))
    op.drop_index(op.f('ix_bet_ledger_status'), table_name='bet_ledger')
    op.drop_index(op.f('ix_bet_ledger_match_id'), table_name='bet_ledger')
    op.drop_index(op.f('ix_bet_ledger_idempotency_key'), table_name='bet_ledger')
    op.drop_index(op.f('ix_bet_ledger_exchange_bet_id'), table_name='bet_ledger')
    op.drop_index('ix_bet_ledger_account_status', table_name='bet_ledger')
    op.drop_index('ix_bet_ledger_account_placed_at', table_name='bet_ledger')
    op.drop_table('bet_ledger')
    op.drop_table('risk_mandates')
    op.drop_index(op.f('ix_exchange_accounts_user_id'), table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
