"""nalanda tick lake and settlement warehouse

Group 67. Three partition trees, RANGE over their time column, one partition per ISO week, BRIN on
that column: nalanda_ticks, nalanda_ohlcv_1m, nalanda_settlement_archive (the hash-chained
warehouse, append-only by trigger). Each is created with its DEFAULT partition and the current week
and the eight after it; from then on the partition pre-allocator (Celery Beat, Sundays, and the
in-process housekeeper) keeps the weeks ahead. Plus the bookkeeping tables (chain head, mirror index
and cursors, cold-export manifest, rollup and maintenance logs).

Revision ID: 5e4e1106d21a
Revises: 4d1e44adf936
Create Date: 2026-10-09 14:36:20.066521

"""
from typing import Sequence, Union

from datetime import UTC, date, datetime, timedelta

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e4e1106d21a'
down_revision: Union[str, Sequence[str], None] = '4d1e44adf936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PARTITIONED = ("nalanda_ticks", "nalanda_ohlcv_1m", "nalanda_settlement_archive")
APPEND_ONLY_FUNCTION = """
CREATE OR REPLACE FUNCTION nalanda_append_only() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN
    RAISE EXCEPTION 'nalanda: % is append-only; % refused', TG_TABLE_NAME, TG_OP USING ERRCODE = 'insufficient_privilege';
END
$body$
"""


def _monday(day: date) -> date:
    return day - timedelta(days=day.isoweekday() - 1)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nalanda_chain_state',
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.Column('last_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain', name=op.f('pk_nalanda_chain_state'))
    )
    op.create_table('nalanda_cold_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('partition_name', sa.String(length=96), nullable=True),
    sa.Column('range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('rows', sa.BigInteger(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mirror_target', sa.Text(), nullable=True),
    sa.Column('mirrored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('EXPORTED', 'DROPPED', 'BACKUP', 'FAILED')", name=op.f('ck_nalanda_cold_exports_status_known')),
    sa.CheckConstraint('rows >= 0 AND bytes >= 0', name=op.f('ck_nalanda_cold_exports_sizes_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nalanda_cold_exports'))
    )
    op.create_table('nalanda_maintenance_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nalanda_maintenance_log'))
    )
    op.create_index('ix_nalanda_maintenance_log_task', 'nalanda_maintenance_log', ['task', 'started_at'], unique=False)
    op.create_table('nalanda_mirror_cursors',
    sa.Column('record_kind', sa.String(length=32), nullable=False),
    sa.Column('watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mirrored', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('record_kind', name=op.f('pk_nalanda_mirror_cursors'))
    )
    op.create_table('nalanda_mirror_index',
    sa.Column('record_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('record_kind', 'source_id', name=op.f('pk_nalanda_mirror_index'))
    )
    op.create_table('nalanda_ohlcv_1m',
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=64), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ticks', sa.Integer(), nullable=False),
    sa.Column('anomalies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('low > 1 AND low <= open AND low <= close AND high >= open AND high >= close', name=op.f('ck_nalanda_ohlcv_1m_ohlc_consistent')),
    sa.CheckConstraint('ticks > 0', name=op.f('ck_nalanda_ohlcv_1m_ticks_positive')),
    postgresql_partition_by='RANGE (bucket_start)'
    )
    op.create_index('ix_nalanda_ohlcv_1m_bucket_start_brin', 'nalanda_ohlcv_1m', ['bucket_start'], unique=False, postgresql_using='brin', postgresql_with={'pages_per_range': 32})
    op.create_index('ix_nalanda_ohlcv_1m_market', 'nalanda_ohlcv_1m', ['fixture_id', 'market'], unique=False)
    op.create_table('nalanda_rollup_log',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ticks', sa.BigInteger(), nullable=False),
    sa.Column('candles', sa.BigInteger(), nullable=False),
    sa.Column('anomalies', sa.BigInteger(), nullable=False),
    sa.Column('rolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_nalanda_rollup_log'))
    )
    op.create_table('nalanda_settlement_archive',
    sa.Column('seq', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('bot_id', sa.Uuid(), nullable=True),
    sa.Column('ledger_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.String(length=128), nullable=True),
    sa.Column('amount_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('length(row_hash) = 64 AND length(prev_hash) = 64', name=op.f('ck_nalanda_settlement_archive_hash_lengths')),
    sa.CheckConstraint('seq >= 1', name=op.f('ck_nalanda_settlement_archive_seq_positive')),
    sa.PrimaryKeyConstraint('seq', 'created_at', name=op.f('pk_nalanda_settlement_archive')),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_nalanda_settlement_archive_created_at_brin', 'nalanda_settlement_archive', ['created_at'], unique=False, postgresql_using='brin', postgresql_with={'pages_per_range': 32})
    op.create_index('ix_nalanda_settlement_archive_kind_user', 'nalanda_settlement_archive', ['record_kind', 'user_id'], unique=False)
    op.create_index('ix_nalanda_settlement_archive_ledger', 'nalanda_settlement_archive', ['ledger_id'], unique=False)
    op.create_table('nalanda_ticks',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=64), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_z', sa.Float(), nullable=True),
    sa.Column('stream_id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('odds > 1', name=op.f('ck_nalanda_ticks_odds_above_one')),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_nalanda_ticks_created_at_brin', 'nalanda_ticks', ['created_at'], unique=False, postgresql_using='brin', postgresql_with={'pages_per_range': 32})
    op.create_index('ix_nalanda_ticks_market', 'nalanda_ticks', ['fixture_id', 'market'], unique=False)
    # ### end Alembic commands ###

    # The warehouse is append-only: UPDATE, DELETE and TRUNCATE are refused (the hash chain proves it held)
    op.execute(APPEND_ONLY_FUNCTION)
    op.execute("CREATE TRIGGER nalanda_settlement_archive_append_only BEFORE UPDATE OR DELETE ON nalanda_settlement_archive FOR EACH ROW EXECUTE FUNCTION nalanda_append_only()")
    op.execute("CREATE TRIGGER nalanda_settlement_archive_no_truncate BEFORE TRUNCATE ON nalanda_settlement_archive FOR EACH STATEMENT EXECUTE FUNCTION nalanda_append_only()")
    # Every tree: its DEFAULT partition (an insert never fails) and the weeks from this one to eight ahead
    monday = _monday(datetime.now(UTC).date())
    for table in PARTITIONED:
        op.execute(f"CREATE TABLE {table}_pdefault PARTITION OF {table} DEFAULT")
        for week in range(9):
            lower = monday + timedelta(days=7 * week)
            iso = lower.isocalendar()
            upper = lower + timedelta(days=7)
            op.execute(
                f"CREATE TABLE {table}_p{iso.year}w{iso.week:02d} PARTITION OF {table} "
                f"FOR VALUES FROM ('{lower.isoformat()}T00:00:00+00:00') TO ('{upper.isoformat()}T00:00:00+00:00')"
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (dropping a partition tree drops every partition in it)
    op.drop_index('ix_nalanda_ticks_market', table_name='nalanda_ticks')
    op.drop_index('ix_nalanda_ticks_created_at_brin', table_name='nalanda_ticks', postgresql_using='brin', postgresql_with={'pages_per_range': 32})
    op.drop_table('nalanda_ticks')
    op.drop_index('ix_nalanda_settlement_archive_ledger', table_name='nalanda_settlement_archive')
    op.drop_index('ix_nalanda_settlement_archive_kind_user', table_name='nalanda_settlement_archive')
    op.drop_index('ix_nalanda_settlement_archive_created_at_brin', table_name='nalanda_settlement_archive', postgresql_using='brin', postgresql_with={'pages_per_range': 32})
    op.drop_table('nalanda_settlement_archive')
    op.drop_table('nalanda_rollup_log')
    op.drop_index('ix_nalanda_ohlcv_1m_market', table_name='nalanda_ohlcv_1m')
    op.drop_index('ix_nalanda_ohlcv_1m_bucket_start_brin', table_name='nalanda_ohlcv_1m', postgresql_using='brin', postgresql_with={'pages_per_range': 32})
    op.drop_table('nalanda_ohlcv_1m')
    op.drop_table('nalanda_mirror_index')
    op.drop_table('nalanda_mirror_cursors')
    op.drop_index('ix_nalanda_maintenance_log_task', table_name='nalanda_maintenance_log')
    op.drop_table('nalanda_maintenance_log')
    op.drop_table('nalanda_cold_exports')
    op.drop_table('nalanda_chain_state')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS nalanda_append_only()")
