"""group_47_control_panel

Revision ID: 5e83c9f33403
Revises: 819963d761ae
Create Date: 2026-09-30 13:09:17.008432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e83c9f33403'
down_revision: Union[str, Sequence[str], None] = '819963d761ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('developer_name', sa.String(length=128), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('build_info', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('accent_color', sa.String(length=16), nullable=False),
    sa.Column('reduce_motion', sa.Boolean(), nullable=False),
    sa.Column('odds_api_key', sa.String(length=128), nullable=True),
    sa.Column('news_api_key', sa.String(length=128), nullable=True),
    sa.Column('omniroute_url', sa.String(length=255), nullable=True),
    sa.Column('bots_enabled', sa.Boolean(), nullable=False),
    sa.Column('research_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('default_kelly_fraction', sa.Float(), nullable=False),
    sa.Column('global_stop_loss', sa.Float(), nullable=False),
    sa.Column('max_bet_size', sa.Float(), nullable=False),
    sa.Column('max_daily_exposure', sa.Float(), nullable=False),
    sa.Column('last_emergency_stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("theme IN ('light', 'dark', 'auto')", name=op.f('ck_system_settings_ck_theme')),
    sa.CheckConstraint('default_kelly_fraction >= 0.0 AND default_kelly_fraction <= 1.0', name=op.f('ck_system_settings_ck_kelly')),
    sa.CheckConstraint('global_stop_loss >= 0.0', name=op.f('ck_system_settings_ck_stop_loss')),
    sa.CheckConstraint('id = 1', name=op.f('ck_system_settings_ck_singleton')),
    sa.CheckConstraint('length(accent_color) BETWEEN 4 AND 16', name=op.f('ck_system_settings_ck_accent_color_length')),
    sa.CheckConstraint('max_bet_size >= 0.0', name=op.f('ck_system_settings_ck_max_bet')),
    sa.CheckConstraint('max_daily_exposure >= 0.0', name=op.f('ck_system_settings_ck_max_exposure')),
    sa.CheckConstraint('research_frequency_minutes >= 1', name=op.f('ck_system_settings_ck_research_frequency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
