"""group_41_the_hive

Revision ID: 7dbeda2fb371
Revises: 1a373103a51e
Create Date: 2026-09-29 22:12:25.442028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dbeda2fb371'
down_revision: Union[str, Sequence[str], None] = '1a373103a51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hive_bot_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bot_name', sa.Enum('KAUTILYA', 'ASHOKA', 'KUMBHA', 'PANINI', 'SHIVAJI', 'PRITHVIRAJ', 'BIRBAL', 'PORUS', 'ARYABHATA', 'TODAR MAL', 'VIDUR', 'BAJIRAO', 'PRATAP', 'VARAHMIHIR', 'GARUDA', 'VIKRAMADITYA', 'KAPILENDRADEVA', name='hive_legendary_bot', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'SLEEPING', 'WORKING', 'DEGRADED', 'FATAL', name='hive_bot_status', create_constraint=True), nullable=False),
    sa.Column('uptime_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resource_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('error_count >= 0', name=op.f('ck_hive_bot_profiles_ck_hive_bot_error_count_non_negative')),
    sa.CheckConstraint('tasks_completed >= 0', name=op.f('ck_hive_bot_profiles_ck_hive_bot_tasks_completed_non_negative')),
    sa.CheckConstraint('uptime_seconds >= 0', name=op.f('ck_hive_bot_profiles_ck_hive_bot_uptime_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_bot_profiles')),
    sa.UniqueConstraint('bot_name', name=op.f('uq_hive_bot_profiles_bot_name'))
    )
    op.create_index(op.f('ix_hive_bot_profiles_last_ping_at'), 'hive_bot_profiles', ['last_ping_at'], unique=False)
    op.create_index(op.f('ix_hive_bot_profiles_status'), 'hive_bot_profiles', ['status'], unique=False)
    op.create_table('hive_self_learning_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bot_name', sa.Enum('KAUTILYA', 'ASHOKA', 'KUMBHA', 'PANINI', 'SHIVAJI', 'PRITHVIRAJ', 'BIRBAL', 'PORUS', 'ARYABHATA', 'TODAR MAL', 'VIDUR', 'BAJIRAO', 'PRATAP', 'VARAHMIHIR', 'GARUDA', 'VIKRAMADITYA', 'KAPILENDRADEVA', name='hive_legendary_bot', create_constraint=True), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name=op.f('ck_hive_self_learning_logs_ck_hive_learning_confidence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_self_learning_logs'))
    )
    op.create_index('ix_hive_learning_bot_param_created', 'hive_self_learning_logs', ['bot_name', 'parameter_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_hive_self_learning_logs_bot_name'), 'hive_self_learning_logs', ['bot_name'], unique=False)
    op.create_index(op.f('ix_hive_self_learning_logs_created_at'), 'hive_self_learning_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_hive_self_learning_logs_parameter_name'), 'hive_self_learning_logs', ['parameter_name'], unique=False)
    op.create_table('hive_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_name', sa.Enum('KAUTILYA', 'ASHOKA', 'KUMBHA', 'PANINI', 'SHIVAJI', 'PRITHVIRAJ', 'BIRBAL', 'PORUS', 'ARYABHATA', 'TODAR MAL', 'VIDUR', 'BAJIRAO', 'PRATAP', 'VARAHMIHIR', 'GARUDA', 'VIKRAMADITYA', 'KAPILENDRADEVA', name='hive_legendary_bot', create_constraint=True), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'IN_PROGRESS', 'REVIEW', 'DONE', 'FAILED', 'BLOCKED', 'EXPIRED', name='hive_task_status', create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_payload', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_retries >= 0', name=op.f('ck_hive_tasks_ck_hive_task_max_retries_non_negative')),
    sa.CheckConstraint('priority >= 0 AND priority <= 100', name=op.f('ck_hive_tasks_ck_hive_task_priority_range')),
    sa.CheckConstraint('retry_count >= 0 AND retry_count <= max_retries', name=op.f('ck_hive_tasks_ck_hive_task_retry_count_bounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_tasks'))
    )
    op.create_index('ix_hive_task_payload_gin', 'hive_tasks', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_hive_task_result_payload_gin', 'hive_tasks', ['result_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_hive_task_status_priority', 'hive_tasks', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_hive_tasks_assignee_name'), 'hive_tasks', ['assignee_name'], unique=False)
    op.create_index(op.f('ix_hive_tasks_created_at'), 'hive_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_hive_tasks_expires_at'), 'hive_tasks', ['expires_at'], unique=False)
    op.create_table('hive_task_dependencies',
    sa.Column('parent_task_id', sa.Uuid(), nullable=False),
    sa.Column('child_task_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('parent_task_id <> child_task_id', name=op.f('ck_hive_task_dependencies_ck_hive_dependency_no_self_loop')),
    sa.ForeignKeyConstraint(['child_task_id'], ['hive_tasks.id'], name=op.f('fk_hive_task_dependencies_child_task_id_hive_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['hive_tasks.id'], name=op.f('fk_hive_task_dependencies_parent_task_id_hive_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_task_id', 'child_task_id', name=op.f('pk_hive_task_dependencies'))
    )
    op.create_index('ix_hive_task_dependencies_child', 'hive_task_dependencies', ['child_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hive_task_dependencies_child', table_name='hive_task_dependencies')
    op.drop_table('hive_task_dependencies')
    op.drop_index(op.f('ix_hive_tasks_expires_at'), table_name='hive_tasks')
    op.drop_index(op.f('ix_hive_tasks_created_at'), table_name='hive_tasks')
    op.drop_index(op.f('ix_hive_tasks_assignee_name'), table_name='hive_tasks')
    op.drop_index('ix_hive_task_status_priority', table_name='hive_tasks')
    op.drop_index('ix_hive_task_result_payload_gin', table_name='hive_tasks', postgresql_using='gin')
    op.drop_index('ix_hive_task_payload_gin', table_name='hive_tasks', postgresql_using='gin')
    op.drop_table('hive_tasks')
    op.drop_index(op.f('ix_hive_self_learning_logs_parameter_name'), table_name='hive_self_learning_logs')
    op.drop_index(op.f('ix_hive_self_learning_logs_created_at'), table_name='hive_self_learning_logs')
    op.drop_index(op.f('ix_hive_self_learning_logs_bot_name'), table_name='hive_self_learning_logs')
    op.drop_index('ix_hive_learning_bot_param_created', table_name='hive_self_learning_logs')
    op.drop_table('hive_self_learning_logs')
    op.drop_index(op.f('ix_hive_bot_profiles_status'), table_name='hive_bot_profiles')
    op.drop_index(op.f('ix_hive_bot_profiles_last_ping_at'), table_name='hive_bot_profiles')
    op.drop_table('hive_bot_profiles')
    # ### end Alembic commands ###
