"""group_46_archive

Revision ID: 819963d761ae
Revises: dd88d1b0c0a9
Create Date: 2026-09-30 12:37:13.419783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819963d761ae'
down_revision: Union[str, Sequence[str], None] = 'dd88d1b0c0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_access_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_resource', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('VIEW_TABLE', 'INTEGRITY_CHECK')", name=op.f('ck_archive_access_logs_ck_archive_access_logs_action')),
    sa.CheckConstraint('length(target_resource) > 0', name=op.f('ck_archive_access_logs_ck_archive_access_logs_target_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_access_logs'))
    )
    op.create_index(op.f('ix_archive_access_logs_created_at'), 'archive_access_logs', ['created_at'], unique=False)
    op.create_index('ix_archive_access_logs_target_created', 'archive_access_logs', ['target_resource', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_archive_access_logs_target_created', table_name='archive_access_logs')
    op.drop_index(op.f('ix_archive_access_logs_created_at'), table_name='archive_access_logs')
    op.drop_table('archive_access_logs')
    # ### end Alembic commands ###
