"""group_42_the_core

Revision ID: 85734883047b
Revises: 7dbeda2fb371
Create Date: 2026-09-29 23:52:29.877960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85734883047b'
down_revision: Union[str, Sequence[str], None] = '7dbeda2fb371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_engine_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=False),
    sa.Column('memory_usage_mb', sa.Integer(), nullable=False),
    sa.Column('queue_depth', sa.Integer(), nullable=False),
    sa.Column('active_models_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('active_models_count >= 0', name=op.f('ck_core_engine_metrics_ck_core_metrics_models_non_negative')),
    sa.CheckConstraint('cpu_usage_pct >= 0 AND cpu_usage_pct <= 100', name=op.f('ck_core_engine_metrics_ck_core_metrics_cpu_range')),
    sa.CheckConstraint('memory_usage_mb >= 0', name=op.f('ck_core_engine_metrics_ck_core_metrics_memory_non_negative')),
    sa.CheckConstraint('queue_depth >= 0', name=op.f('ck_core_engine_metrics_ck_core_metrics_queue_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_engine_metrics'))
    )
    op.create_index('ix_core_engine_metrics_recorded_at', 'core_engine_metrics', ['recorded_at'], unique=False)
    op.create_table('core_smallcase_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pipeline_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STANDBY', 'DISABLED', name='core_smallcase_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('current_accuracy', sa.Float(), nullable=False),
    sa.Column('cross_val_score', sa.Float(), nullable=False),
    sa.Column('total_backtests_run', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(pipeline_config) = 'array'", name=op.f('ck_core_smallcase_registry_ck_core_smallcase_pipeline_is_array')),
    sa.CheckConstraint('cross_val_score >= 0 AND cross_val_score <= 1', name=op.f('ck_core_smallcase_registry_ck_core_smallcase_cross_val_range')),
    sa.CheckConstraint('current_accuracy >= 0 AND current_accuracy <= 1', name=op.f('ck_core_smallcase_registry_ck_core_smallcase_accuracy_range')),
    sa.CheckConstraint('length(name) > 0', name=op.f('ck_core_smallcase_registry_ck_core_smallcase_name_not_empty')),
    sa.CheckConstraint('total_backtests_run >= 0', name=op.f('ck_core_smallcase_registry_ck_core_smallcase_backtests_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_smallcase_registry')),
    sa.UniqueConstraint('name', name=op.f('uq_core_smallcase_registry_name'))
    )
    op.create_index('ix_core_smallcase_pipeline_config_gin', 'core_smallcase_registry', ['pipeline_config'], unique=False, postgresql_using='gin')
    op.create_index('ix_core_smallcase_status', 'core_smallcase_registry', ['status'], unique=False)
    op.create_table('core_backtest_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('smallcase_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_matches_simulated', sa.Integer(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=True),
    sa.Column('accuracy_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='core_backtest_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('accuracy_pct IS NULL OR (accuracy_pct >= 0 AND accuracy_pct <= 100)', name=op.f('ck_core_backtest_jobs_ck_core_backtest_accuracy_range')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_core_backtest_jobs_ck_core_backtest_date_order')),
    sa.CheckConstraint('max_drawdown_pct IS NULL OR (max_drawdown_pct >= 0 AND max_drawdown_pct <= 100)', name=op.f('ck_core_backtest_jobs_ck_core_backtest_drawdown_range')),
    sa.CheckConstraint('roi_pct IS NULL OR roi_pct >= -100', name=op.f('ck_core_backtest_jobs_ck_core_backtest_roi_floor')),
    sa.CheckConstraint('total_matches_simulated >= 0', name=op.f('ck_core_backtest_jobs_ck_core_backtest_matches_non_negative')),
    sa.ForeignKeyConstraint(['smallcase_id'], ['core_smallcase_registry.id'], name=op.f('fk_core_backtest_jobs_smallcase_id_core_smallcase_registry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_backtest_jobs'))
    )
    op.create_index('ix_core_backtest_jobs_smallcase_created', 'core_backtest_jobs', ['smallcase_id', 'created_at'], unique=False)
    op.create_index('ix_core_backtest_jobs_status', 'core_backtest_jobs', ['status'], unique=False)
    op.create_table('core_test_bench_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('smallcase_id', sa.Uuid(), nullable=False),
    sa.Column('match_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pipeline_execution_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('predicted_outcome', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='core_test_bench_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_stress_test', sa.Boolean(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("jsonb_typeof(match_context) = 'object'", name=op.f('ck_core_test_bench_runs_ck_core_test_bench_context_is_object')),
    sa.CheckConstraint("jsonb_typeof(pipeline_execution_steps) = 'array'", name=op.f('ck_core_test_bench_runs_ck_core_test_bench_steps_is_array')),
    sa.CheckConstraint('execution_time_ms IS NULL OR execution_time_ms >= 0', name=op.f('ck_core_test_bench_runs_ck_core_test_bench_exec_time')),
    sa.ForeignKeyConstraint(['smallcase_id'], ['core_smallcase_registry.id'], name=op.f('fk_core_test_bench_runs_smallcase_id_core_smallcase_registry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_test_bench_runs'))
    )
    op.create_index('ix_core_test_bench_runs_match_context_gin', 'core_test_bench_runs', ['match_context'], unique=False, postgresql_using='gin')
    op.create_index('ix_core_test_bench_runs_predicted_outcome_gin', 'core_test_bench_runs', ['predicted_outcome'], unique=False, postgresql_using='gin')
    op.create_index('ix_core_test_bench_runs_smallcase_created', 'core_test_bench_runs', ['smallcase_id', 'created_at'], unique=False)
    op.create_index('ix_core_test_bench_runs_status', 'core_test_bench_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_core_test_bench_runs_status', table_name='core_test_bench_runs')
    op.drop_index('ix_core_test_bench_runs_smallcase_created', table_name='core_test_bench_runs')
    op.drop_index('ix_core_test_bench_runs_predicted_outcome_gin', table_name='core_test_bench_runs', postgresql_using='gin')
    op.drop_index('ix_core_test_bench_runs_match_context_gin', table_name='core_test_bench_runs', postgresql_using='gin')
    op.drop_table('core_test_bench_runs')
    op.drop_index('ix_core_backtest_jobs_status', table_name='core_backtest_jobs')
    op.drop_index('ix_core_backtest_jobs_smallcase_created', table_name='core_backtest_jobs')
    op.drop_table('core_backtest_jobs')
    op.drop_index('ix_core_smallcase_status', table_name='core_smallcase_registry')
    op.drop_index('ix_core_smallcase_pipeline_config_gin', table_name='core_smallcase_registry', postgresql_using='gin')
    op.drop_table('core_smallcase_registry')
    op.drop_index('ix_core_engine_metrics_recorded_at', table_name='core_engine_metrics')
    op.drop_table('core_engine_metrics')
    # ### end Alembic commands ###
