"""hive trading bots and sub accounts

Group 65 (The Hive): trading bots, their decision log, TWAP order plans and shadow positions.
The CFO ledger gains isolated sub-accounts (one per bot: bankroll rows, journal entries and bets
carry ``bot_id``), the ALLOCATE / DEALLOCATE postings, and one-main-account-per-user becomes a
partial unique index. The model registry (``core_smallcase_registry``) gains component rows.

Revision ID: 9c83ee5f76f2
Revises: 5c2e8a41f0b7
Create Date: 2026-10-09 10:42:47.958811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

POSTING_KINDS = ("OPEN", "RESERVE", "RELEASE", "SETTLE_WON", "SETTLE_LOST")
POSTING_KINDS_G65 = POSTING_KINDS + ("ALLOCATE", "DEALLOCATE")
COMPONENT_KINDS = ("PIPELINE", "MATH_MODEL", "RISK_MODEL", "BET_TYPE")


def _in(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{v}'" for v in values)

# revision identifiers, used by Alembic.
revision: str = '9c83ee5f76f2'
down_revision: Union[str, Sequence[str], None] = '5c2e8a41f0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hive_trading_bots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Enum('PAPER_TRADE', 'SHADOW_MODE', 'LIVE_EXECUTION', name='hive_bot_execution_mode', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'SUSPENDED', 'ARCHIVED', name='hive_bot_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('math_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_bet_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allocated_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('kelly_multiplier', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_stake_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_edge_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_quoting_books', sa.Integer(), nullable=False),
    sa.Column('min_market_liquidity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('enable_order_slicing', sa.Boolean(), nullable=False),
    sa.Column('slice_size_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_bets_per_minute', sa.Integer(), nullable=False),
    sa.Column('drawdown_limit_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('suspended_reason', sa.String(length=64), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_capital >= 0', name=op.f('ck_hive_trading_bots_allocation_non_negative')),
    sa.CheckConstraint('cooldown_seconds >= 0', name=op.f('ck_hive_trading_bots_cooldown_non_negative')),
    sa.CheckConstraint('drawdown_limit_pct >= 1 AND drawdown_limit_pct <= 90', name=op.f('ck_hive_trading_bots_drawdown_range')),
    sa.CheckConstraint('kelly_multiplier > 0 AND kelly_multiplier <= 1', name=op.f('ck_hive_trading_bots_kelly_range')),
    sa.CheckConstraint('max_bets_per_minute >= 1 AND max_bets_per_minute <= 20', name=op.f('ck_hive_trading_bots_velocity_range')),
    sa.CheckConstraint('max_stake_pct >= 0.1 AND max_stake_pct <= 25', name=op.f('ck_hive_trading_bots_stake_pct_range')),
    sa.CheckConstraint('min_edge_pct >= 0.5 AND min_edge_pct <= 25', name=op.f('ck_hive_trading_bots_edge_range')),
    sa.CheckConstraint('min_market_liquidity >= 0', name=op.f('ck_hive_trading_bots_liquidity_non_negative')),
    sa.CheckConstraint('min_quoting_books >= 1 AND min_quoting_books <= 50', name=op.f('ck_hive_trading_bots_books_range')),
    sa.CheckConstraint('slice_size_inr > 0', name=op.f('ck_hive_trading_bots_slice_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hive_trading_bots_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_trading_bots')),
    sa.UniqueConstraint('user_id', 'name', name='uq_hive_trading_bots_user_name')
    )
    op.create_index('ix_hive_trading_bots_status', 'hive_trading_bots', ['status'], unique=False)
    op.create_table('hive_bot_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.Enum('FIRED', 'SHADOW_FILLED', 'SLICED', 'SLICE_FIRED', 'SLICE_CANCELLED', 'MERGED', 'BLOCKED', 'SKIPPED', 'SUSPENDED', 'HALTED', 'ALLOCATED', name='hive_event_kind', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.String(length=128), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('selection', sa.String(length=64), nullable=True),
    sa.Column('stake_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('conviction', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['hive_trading_bots.id'], name=op.f('fk_hive_bot_events_bot_id_hive_trading_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hive_bot_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_bot_events'))
    )
    op.create_index('ix_hive_bot_events_bot_created', 'hive_bot_events', ['bot_id', 'created_at'], unique=False)
    op.create_index('ix_hive_bot_events_user_created', 'hive_bot_events', ['user_id', 'created_at'], unique=False)
    op.create_table('hive_order_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=64), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('true_prob', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_stake_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('slices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'RUNNING', 'COMPLETE', 'CANCELLED', name='hive_plan_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_stake_inr > 0', name=op.f('ck_hive_order_plans_total_positive')),
    sa.ForeignKeyConstraint(['bot_id'], ['hive_trading_bots.id'], name=op.f('fk_hive_order_plans_bot_id_hive_trading_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hive_order_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_order_plans'))
    )
    op.create_index('ix_hive_order_plans_bot_status', 'hive_order_plans', ['bot_id', 'status'], unique=False)
    op.create_table('hive_shadow_positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=64), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stake_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('true_prob', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'WON', 'LOST', 'VOID', name='hive_shadow_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('pnl_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('odds > 1', name=op.f('ck_hive_shadow_positions_odds_above_one')),
    sa.CheckConstraint('stake_inr > 0', name=op.f('ck_hive_shadow_positions_stake_positive')),
    sa.ForeignKeyConstraint(['bot_id'], ['hive_trading_bots.id'], name=op.f('fk_hive_shadow_positions_bot_id_hive_trading_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hive_shadow_positions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hive_shadow_positions'))
    )
    op.create_index('ix_hive_shadow_positions_bot_status', 'hive_shadow_positions', ['bot_id', 'status'], unique=False)
    op.create_index('ix_hive_shadow_positions_fixture_status', 'hive_shadow_positions', ['fixture_id', 'market', 'status'], unique=False)
    op.add_column('cfo_bankroll_accounts', sa.Column('bot_id', sa.Uuid(), nullable=True))
    op.add_column('cfo_bankroll_accounts', sa.Column('funding', sa.String(length=16), nullable=True))
    op.create_check_constraint(
        'funding_for_bots', 'cfo_bankroll_accounts', "(bot_id IS NULL AND funding IS NULL) OR (bot_id IS NOT NULL AND funding IS NOT NULL)"
    )
    op.drop_constraint(op.f('uq_cfo_bankroll_accounts_user_id'), 'cfo_bankroll_accounts', type_='unique')
    op.create_index('uq_cfo_bankroll_accounts_bot', 'cfo_bankroll_accounts', ['bot_id'], unique=True, postgresql_where=sa.text('bot_id IS NOT NULL'), sqlite_where=sa.text('bot_id IS NOT NULL'))
    op.create_index('uq_cfo_bankroll_accounts_main', 'cfo_bankroll_accounts', ['user_id'], unique=True, postgresql_where=sa.text('bot_id IS NULL'), sqlite_where=sa.text('bot_id IS NULL'))
    op.create_foreign_key(op.f('fk_cfo_bankroll_accounts_bot_id_hive_trading_bots'), 'cfo_bankroll_accounts', 'hive_trading_bots', ['bot_id'], ['id'], ondelete='RESTRICT')
    op.add_column('cfo_ledger_entries', sa.Column('bot_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('ck_cfo_ledger_entries_cfo_posting_kind'), 'cfo_ledger_entries', type_='check')
    op.create_check_constraint('cfo_posting_kind', 'cfo_ledger_entries', f"kind IN ({_in(POSTING_KINDS_G65)})")
    op.create_index('ix_cfo_ledger_entries_user_bot_account', 'cfo_ledger_entries', ['user_id', 'bot_id', 'account'], unique=False)
    op.create_foreign_key(op.f('fk_cfo_ledger_entries_bot_id_hive_trading_bots'), 'cfo_ledger_entries', 'hive_trading_bots', ['bot_id'], ['id'], ondelete='RESTRICT')
    op.add_column('cfo_phantom_ledger', sa.Column('bot_id', sa.Uuid(), nullable=True))
    op.create_index('ix_cfo_phantom_ledger_bot_status', 'cfo_phantom_ledger', ['bot_id', 'status'], unique=False)
    op.create_foreign_key(op.f('fk_cfo_phantom_ledger_bot_id_hive_trading_bots'), 'cfo_phantom_ledger', 'hive_trading_bots', ['bot_id'], ['id'], ondelete='RESTRICT')
    op.add_column('core_smallcase_registry', sa.Column('component_kind', sa.String(length=16), server_default='PIPELINE', nullable=False))
    op.create_check_constraint('core_component_kind', 'core_smallcase_registry', f"component_kind IN ({_in(COMPONENT_KINDS)})")
    op.add_column('core_smallcase_registry', sa.Column('component_key', sa.String(length=96), nullable=True))
    op.add_column('core_smallcase_registry', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('core_smallcase_registry', sa.Column('implementation', sa.String(length=255), nullable=True))
    op.add_column('core_smallcase_registry', sa.Column('live_capable', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('core_smallcase_registry', sa.Column('catalogue_source', sa.String(length=32), server_default='core', nullable=False))
    op.create_unique_constraint(op.f('uq_core_smallcase_registry_component_key'), 'core_smallcase_registry', ['component_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_core_smallcase_registry_component_key'), 'core_smallcase_registry', type_='unique')
    op.execute("DELETE FROM core_smallcase_registry WHERE component_kind <> 'PIPELINE'")
    op.drop_constraint(op.f('ck_core_smallcase_registry_core_component_kind'), 'core_smallcase_registry', type_='check')
    op.drop_column('core_smallcase_registry', 'catalogue_source')
    op.drop_column('core_smallcase_registry', 'live_capable')
    op.drop_column('core_smallcase_registry', 'implementation')
    op.drop_column('core_smallcase_registry', 'category')
    op.drop_column('core_smallcase_registry', 'component_key')
    op.drop_column('core_smallcase_registry', 'component_kind')
    op.drop_constraint(op.f('fk_cfo_phantom_ledger_bot_id_hive_trading_bots'), 'cfo_phantom_ledger', type_='foreignkey')
    op.drop_index('ix_cfo_phantom_ledger_bot_status', table_name='cfo_phantom_ledger')
    op.drop_column('cfo_phantom_ledger', 'bot_id')
    op.drop_constraint(op.f('fk_cfo_ledger_entries_bot_id_hive_trading_bots'), 'cfo_ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('ck_cfo_ledger_entries_cfo_posting_kind'), 'cfo_ledger_entries', type_='check')
    op.create_check_constraint('cfo_posting_kind', 'cfo_ledger_entries', f"kind IN ({_in(POSTING_KINDS)})")
    op.drop_index('ix_cfo_ledger_entries_user_bot_account', table_name='cfo_ledger_entries')
    op.drop_column('cfo_ledger_entries', 'bot_id')
    op.drop_constraint(op.f('fk_cfo_bankroll_accounts_bot_id_hive_trading_bots'), 'cfo_bankroll_accounts', type_='foreignkey')
    op.drop_constraint(op.f('ck_cfo_bankroll_accounts_funding_for_bots'), 'cfo_bankroll_accounts', type_='check')
    op.drop_index('uq_cfo_bankroll_accounts_main', table_name='cfo_bankroll_accounts', postgresql_where=sa.text('bot_id IS NULL'), sqlite_where=sa.text('bot_id IS NULL'))
    op.drop_index('uq_cfo_bankroll_accounts_bot', table_name='cfo_bankroll_accounts', postgresql_where=sa.text('bot_id IS NOT NULL'), sqlite_where=sa.text('bot_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_cfo_bankroll_accounts_user_id'), 'cfo_bankroll_accounts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cfo_bankroll_accounts', 'funding')
    op.drop_column('cfo_bankroll_accounts', 'bot_id')
    op.drop_index('ix_hive_shadow_positions_fixture_status', table_name='hive_shadow_positions')
    op.drop_index('ix_hive_shadow_positions_bot_status', table_name='hive_shadow_positions')
    op.drop_table('hive_shadow_positions')
    op.drop_index('ix_hive_order_plans_bot_status', table_name='hive_order_plans')
    op.drop_table('hive_order_plans')
    op.drop_index('ix_hive_bot_events_user_created', table_name='hive_bot_events')
    op.drop_index('ix_hive_bot_events_bot_created', table_name='hive_bot_events')
    op.drop_table('hive_bot_events')
    op.drop_index('ix_hive_trading_bots_status', table_name='hive_trading_bots')
    op.drop_table('hive_trading_bots')
    # ### end Alembic commands ###
