"""groups 54-58 bookmakers cfo human touch phantom sports tables

These five feature sets shipped models, routers and tests but no migration, so every request
against a migrated database failed with "relation does not exist". Autogenerated from the
models, then reviewed.

Revision ID: a71c0e5d9b22
Revises: f3a9c1d27b40
Create Date: 2026-10-08 00:05:14.945279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71c0e5d9b22'
down_revision: Union[str, Sequence[str], None] = 'f3a9c1d27b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmaker_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('priority_rank', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(name) > 0', name=op.f('ck_bookmaker_configs_ck_bookmaker_configs_name_not_empty')),
    sa.CheckConstraint('priority_rank >= 1', name=op.f('ck_bookmaker_configs_ck_bookmaker_configs_priority_rank_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmaker_configs'))
    )
    op.create_index(op.f('ix_bookmaker_configs_name'), 'bookmaker_configs', ['name'], unique=True)
    op.create_table('cfo_advisories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('capital_health_score', sa.Float(), nullable=False),
    sa.Column('variance_status', sa.String(length=32), nullable=False),
    sa.Column('suggestions_json', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("variance_status IN ('HIGH', 'STABLE')", name=op.f('ck_cfo_advisories_ck_cfo_advisory_variance_status')),
    sa.CheckConstraint('capital_health_score >= 0 AND capital_health_score <= 100', name=op.f('ck_cfo_advisories_ck_cfo_advisory_health_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_advisories'))
    )
    op.create_index('ix_cfo_advisories_user_created', 'cfo_advisories', ['user_id', 'created_at'], unique=False)
    op.create_table('cfo_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('INFO', 'WARNING', 'CRITICAL')", name=op.f('ck_cfo_alerts_ck_cfo_alert_level')),
    sa.CheckConstraint('length(message) > 0', name=op.f('ck_cfo_alerts_ck_cfo_alert_message_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_alerts'))
    )
    op.create_index('ix_cfo_alerts_user_unread_created', 'cfo_alerts', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('cfo_stress_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_name', sa.String(length=64), nullable=False),
    sa.Column('portfolio_value_before', sa.Float(), nullable=False),
    sa.Column('simulated_pnl', sa.Float(), nullable=False),
    sa.Column('simulated_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('survived', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(scenario_name) > 0', name=op.f('ck_cfo_stress_tests_ck_cfo_stress_scenario_not_empty')),
    sa.CheckConstraint('portfolio_value_before > 0', name=op.f('ck_cfo_stress_tests_ck_cfo_stress_portfolio_positive')),
    sa.CheckConstraint('simulated_drawdown_pct >= 0 AND simulated_drawdown_pct <= 100', name=op.f('ck_cfo_stress_tests_ck_cfo_stress_drawdown_range')),
    sa.CheckConstraint('simulated_pnl <= 0', name=op.f('ck_cfo_stress_tests_ck_cfo_stress_pnl_non_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfo_stress_tests'))
    )
    op.create_index('ix_cfo_stress_tests_user_created', 'cfo_stress_tests', ['user_id', 'created_at'], unique=False)
    op.create_table('human_override_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('pure_math_prob', sa.Float(), nullable=False),
    sa.Column('blended_prob', sa.Float(), nullable=False),
    sa.Column('actual_outcome', sa.Float(), nullable=True),
    sa.Column('math_brier_score', sa.Float(), nullable=True),
    sa.Column('blended_brier_score', sa.Float(), nullable=True),
    sa.Column('human_touch_improved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(actual_outcome IS NULL AND math_brier_score IS NULL AND blended_brier_score IS NULL AND resolved_at IS NULL) OR (actual_outcome IS NOT NULL AND math_brier_score IS NOT NULL AND blended_brier_score IS NOT NULL AND resolved_at IS NOT NULL)', name=op.f('ck_human_override_logs_ck_human_override_resolution_consistency')),
    sa.CheckConstraint('actual_outcome IS NULL OR actual_outcome IN (0.0, 0.5, 1.0)', name=op.f('ck_human_override_logs_ck_human_override_outcome_values')),
    sa.CheckConstraint('blended_brier_score IS NULL OR (blended_brier_score >= 0.0 AND blended_brier_score <= 1.0)', name=op.f('ck_human_override_logs_ck_human_override_blended_brier_range')),
    sa.CheckConstraint('blended_prob >= 0.0 AND blended_prob <= 1.0', name=op.f('ck_human_override_logs_ck_human_override_blended_prob_range')),
    sa.CheckConstraint('length(match_id) > 0', name=op.f('ck_human_override_logs_ck_human_override_match_id_not_empty')),
    sa.CheckConstraint('math_brier_score IS NULL OR (math_brier_score >= 0.0 AND math_brier_score <= 1.0)', name=op.f('ck_human_override_logs_ck_human_override_math_brier_range')),
    sa.CheckConstraint('pure_math_prob >= 0.0 AND pure_math_prob <= 1.0', name=op.f('ck_human_override_logs_ck_human_override_pure_prob_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_override_logs'))
    )
    op.create_index(op.f('ix_human_override_logs_match_id'), 'human_override_logs', ['match_id'], unique=False)
    op.create_index('ix_human_override_logs_resolved', 'human_override_logs', ['resolved_at'], unique=False)
    op.create_table('human_touch_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=16), nullable=False),
    sa.Column('is_blended_mode_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_adjustment_limit_pct', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('sentiment_weight', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('momentum_weight', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_adjustment_threshold_pct', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("config_key = 'GLOBAL'", name=op.f('ck_human_touch_config_ck_human_touch_config_singleton')),
    sa.CheckConstraint('max_adjustment_limit_pct >= 0.0 AND max_adjustment_limit_pct <= 25.0', name=op.f('ck_human_touch_config_ck_human_touch_config_max_adjustment_range')),
    sa.CheckConstraint('min_adjustment_threshold_pct <= max_adjustment_limit_pct', name=op.f('ck_human_touch_config_ck_human_touch_config_threshold_within_limit')),
    sa.CheckConstraint('min_adjustment_threshold_pct >= 0.0 AND min_adjustment_threshold_pct <= 5.0', name=op.f('ck_human_touch_config_ck_human_touch_config_min_threshold_range')),
    sa.CheckConstraint('momentum_weight >= 0.0 AND momentum_weight <= 1.0', name=op.f('ck_human_touch_config_ck_human_touch_config_momentum_weight_range')),
    sa.CheckConstraint('sentiment_weight >= 0.0 AND sentiment_weight <= 1.0', name=op.f('ck_human_touch_config_ck_human_touch_config_sentiment_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_touch_config')),
    sa.UniqueConstraint('config_key', name=op.f('uq_human_touch_config_config_key'))
    )
    op.create_table('match_narratives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('derby_intensity', sa.Float(), nullable=False),
    sa.Column('home_crowd_hostility', sa.Float(), nullable=False),
    sa.Column('new_manager_bounce', sa.Float(), nullable=False),
    sa.Column('fatigue_index', sa.Float(), nullable=False),
    sa.Column('injury_impact', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('derby_intensity >= 0.0 AND derby_intensity <= 1.0', name=op.f('ck_match_narratives_ck_match_narratives_derby_intensity_range')),
    sa.CheckConstraint('fatigue_index >= 0.0 AND fatigue_index <= 1.0', name=op.f('ck_match_narratives_ck_match_narratives_fatigue_index_range')),
    sa.CheckConstraint('home_crowd_hostility >= 0.0 AND home_crowd_hostility <= 1.0', name=op.f('ck_match_narratives_ck_match_narratives_home_crowd_hostility_range')),
    sa.CheckConstraint('injury_impact >= 0.0 AND injury_impact <= 1.0', name=op.f('ck_match_narratives_ck_match_narratives_injury_impact_range')),
    sa.CheckConstraint('length(match_id) > 0', name=op.f('ck_match_narratives_ck_match_narratives_match_id_not_empty')),
    sa.CheckConstraint('length(team_name) > 0', name=op.f('ck_match_narratives_ck_match_narratives_team_not_empty')),
    sa.CheckConstraint('new_manager_bounce >= 0.0 AND new_manager_bounce <= 1.0', name=op.f('ck_match_narratives_ck_match_narratives_new_manager_bounce_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_narratives')),
    sa.UniqueConstraint('match_id', 'team_name', name='uq_match_narratives_match_team')
    )
    op.create_index(op.f('ix_match_narratives_match_id'), 'match_narratives', ['match_id'], unique=False)
    op.create_table('phantom_arbitrage_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('total_implied_probability', sa.Float(), nullable=False),
    sa.Column('guaranteed_profit_pct', sa.Float(), nullable=False),
    sa.Column('target_total_stake', sa.Float(), nullable=False),
    sa.Column('stakes_json', sa.String(length=2048), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('guaranteed_profit_pct > 0', name=op.f('ck_phantom_arbitrage_opportunities_ck_phantom_arb_profit_positive')),
    sa.CheckConstraint('length(event_name) > 0', name=op.f('ck_phantom_arbitrage_opportunities_ck_phantom_arb_event_not_empty')),
    sa.CheckConstraint('length(market_type) > 0', name=op.f('ck_phantom_arbitrage_opportunities_ck_phantom_arb_market_not_empty')),
    sa.CheckConstraint('length(stakes_json) >= 2', name=op.f('ck_phantom_arbitrage_opportunities_ck_phantom_arb_stakes_json_not_empty')),
    sa.CheckConstraint('target_total_stake > 0', name=op.f('ck_phantom_arbitrage_opportunities_ck_phantom_arb_stake_positive')),
    sa.CheckConstraint('total_implied_probability > 0 AND total_implied_probability < 1.0', name=op.f('ck_phantom_arbitrage_opportunities_ck_phantom_arb_total_probability_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phantom_arbitrage_opportunities'))
    )
    op.create_index('ix_phantom_arb_active_created', 'phantom_arbitrage_opportunities', ['is_active', 'created_at'], unique=False)
    op.create_table('phantom_calculations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calc_type', sa.String(length=32), nullable=False),
    sa.Column('inputs_json', sa.String(length=2048), nullable=False),
    sa.Column('outputs_json', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("calc_type IN ('DUTCHING', 'MATCHED_BETTING', 'AVELLANEDA', 'COINTEGRATION')", name=op.f('ck_phantom_calculations_ck_phantom_calc_type')),
    sa.CheckConstraint('length(inputs_json) >= 2', name=op.f('ck_phantom_calculations_ck_phantom_calc_inputs_json_length')),
    sa.CheckConstraint('length(outputs_json) >= 2', name=op.f('ck_phantom_calculations_ck_phantom_calc_outputs_json_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phantom_calculations'))
    )
    op.create_index('ix_phantom_calculations_type_created', 'phantom_calculations', ['calc_type', 'created_at'], unique=False)
    op.create_table('sport_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sport_name', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config_json', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(config_json) >= 2', name=op.f('ck_sport_configs_ck_sport_configs_config_json_not_empty')),
    sa.CheckConstraint('length(sport_name) > 0', name=op.f('ck_sport_configs_ck_sport_configs_sport_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sport_configs'))
    )
    op.create_index(op.f('ix_sport_configs_sport_name'), 'sport_configs', ['sport_name'], unique=True)
    op.create_table('tax_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('estimated_tax', sa.Float(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_tax >= 0', name=op.f('ck_tax_records_ck_tax_records_tax_non_negative')),
    sa.CheckConstraint('taxable_amount >= 0', name=op.f('ck_tax_records_ck_tax_records_taxable_non_negative')),
    sa.CheckConstraint('year >= 1900 AND year <= 9999', name=op.f('ck_tax_records_ck_tax_records_year_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_records')),
    sa.UniqueConstraint('user_id', 'year', name='uq_tax_records_user_year')
    )
    op.create_index('uq_tax_records_anonymous_year', 'tax_records', ['year'], unique=True, sqlite_where=sa.text('user_id IS NULL'), postgresql_where=sa.text('user_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tax_records_anonymous_year', table_name='tax_records', sqlite_where=sa.text('user_id IS NULL'), postgresql_where=sa.text('user_id IS NULL'))
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_sport_configs_sport_name'), table_name='sport_configs')
    op.drop_table('sport_configs')
    op.drop_index('ix_phantom_calculations_type_created', table_name='phantom_calculations')
    op.drop_table('phantom_calculations')
    op.drop_index('ix_phantom_arb_active_created', table_name='phantom_arbitrage_opportunities')
    op.drop_table('phantom_arbitrage_opportunities')
    op.drop_index(op.f('ix_match_narratives_match_id'), table_name='match_narratives')
    op.drop_table('match_narratives')
    op.drop_table('human_touch_config')
    op.drop_index('ix_human_override_logs_resolved', table_name='human_override_logs')
    op.drop_index(op.f('ix_human_override_logs_match_id'), table_name='human_override_logs')
    op.drop_table('human_override_logs')
    op.drop_index('ix_cfo_stress_tests_user_created', table_name='cfo_stress_tests')
    op.drop_table('cfo_stress_tests')
    op.drop_index('ix_cfo_alerts_user_unread_created', table_name='cfo_alerts')
    op.drop_table('cfo_alerts')
    op.drop_index('ix_cfo_advisories_user_created', table_name='cfo_advisories')
    op.drop_table('cfo_advisories')
    op.drop_index(op.f('ix_bookmaker_configs_name'), table_name='bookmaker_configs')
    op.drop_table('bookmaker_configs')
    # ### end Alembic commands ###
