"""ashoka user bet ledger scores and trend columns

Revision ID: a79f2b8e4c76
Revises: 02835599ce32
Create Date: 2026-10-09 22:30:53.501014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a79f2b8e4c76'
down_revision: Union[str, Sequence[str], None] = '02835599ce32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_scores',
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('home', sa.String(length=128), nullable=False),
    sa.Column('away', sa.String(length=128), nullable=False),
    sa.Column('sport_key', sa.String(length=64), nullable=True),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('FINAL', 'ABANDONED', 'POSTPONED')", name=op.f('ck_fixture_scores_ck_fixture_scores_status')),
    sa.CheckConstraint('(home_goals IS NULL AND away_goals IS NULL) OR (home_goals >= 0 AND away_goals >= 0)', name=op.f('ck_fixture_scores_ck_fixture_scores_goals')),
    sa.PrimaryKeyConstraint('fixture_id', name=op.f('pk_fixture_scores'))
    )
    op.create_index('ix_fixture_scores_kickoff', 'fixture_scores', ['kickoff'], unique=False)
    op.create_table('user_placed_bets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('slip_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('bookmaker', sa.String(length=16), nullable=False),
    sa.Column('bookmaker_name', sa.String(length=64), nullable=True),
    sa.Column('structure', sa.String(length=16), nullable=False),
    sa.Column('stake_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_stake_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('placed_odds', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('return_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("bookmaker IN ('PARIMATCH', '1XBET', 'STAKE', 'PINNACLE', 'BETFAIR', 'OTHER')", name=op.f('ck_user_placed_bets_ck_user_placed_bets_bookmaker')),
    sa.CheckConstraint("status IN ('PENDING', 'WON', 'HALF_WON', 'VOID', 'HALF_LOST', 'LOST', 'CASHED_OUT')", name=op.f('ck_user_placed_bets_ck_user_placed_bets_status')),
    sa.CheckConstraint("structure IN ('SINGLE', 'DOUBLE', 'TREBLE', 'ACCUMULATOR', 'TRIXIE', 'YANKEE', 'CANADIAN', 'HEINZ')", name=op.f('ck_user_placed_bets_ck_user_placed_bets_structure')),
    sa.CheckConstraint('placed_odds IS NULL OR placed_odds >= 1', name=op.f('ck_user_placed_bets_ck_user_placed_bets_odds')),
    sa.CheckConstraint('stake_inr > 0', name=op.f('ck_user_placed_bets_ck_user_placed_bets_stake_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_placed_bets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_placed_bets'))
    )
    op.create_index('ix_user_placed_bets_user_placed', 'user_placed_bets', ['user_id', 'placed_at'], unique=False)
    op.create_index('ix_user_placed_bets_user_settled', 'user_placed_bets', ['user_id', 'settled_at'], unique=False)
    op.create_index('ix_user_placed_bets_user_status', 'user_placed_bets', ['user_id', 'status'], unique=False)
    op.create_table('user_placed_legs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bet_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('home', sa.String(length=128), nullable=False),
    sa.Column('away', sa.String(length=128), nullable=False),
    sa.Column('sport_key', sa.String(length=64), nullable=True),
    sa.Column('league', sa.String(length=64), nullable=True),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('odds', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fair_probability', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.CheckConstraint('odds >= 1', name=op.f('ck_user_placed_legs_ck_user_placed_legs_odds')),
    sa.ForeignKeyConstraint(['bet_id'], ['user_placed_bets.id'], name=op.f('fk_user_placed_legs_bet_id_user_placed_bets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_placed_legs'))
    )
    op.create_index('ix_user_placed_legs_bet', 'user_placed_legs', ['bet_id'], unique=False)
    op.create_index('ix_user_placed_legs_fixture_result', 'user_placed_legs', ['fixture_id', 'result'], unique=False)
    op.add_column('popular_parlays', sa.Column('category', sa.String(length=16), nullable=True))
    op.add_column('popular_parlays', sa.Column('true_ev_pct', sa.Float(), nullable=True))
    op.add_column('popular_parlays', sa.Column('true_probability', sa.Float(), nullable=True))
    op.add_column('popular_parlays', sa.Column('public_share_pct', sa.Float(), nullable=True))
    op.add_column('popular_parlays', sa.Column('public_share_source', sa.String(length=64), nullable=True))
    op.add_column('popular_parlays', sa.Column('warning', sa.String(length=300), nullable=True))
    op.add_column('popular_parlays', sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###
    # autogenerate does not see new check constraints on an existing table
    op.create_check_constraint(
        op.f('ck_popular_parlays_ck_popular_parlays_category'), 'popular_parlays', "category IS NULL OR category IN ('SHARP_STEAM', 'PUBLIC_TRAP', 'AI_HYBRID')"
    )
    op.create_check_constraint(
        op.f('ck_popular_parlays_ck_popular_parlays_public_share'), 'popular_parlays', 'public_share_pct IS NULL OR (public_share_pct >= 0 AND public_share_pct <= 100)'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_popular_parlays_ck_popular_parlays_public_share'), 'popular_parlays', type_='check')
    op.drop_constraint(op.f('ck_popular_parlays_ck_popular_parlays_category'), 'popular_parlays', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_parlays', 'analysis')
    op.drop_column('popular_parlays', 'warning')
    op.drop_column('popular_parlays', 'public_share_source')
    op.drop_column('popular_parlays', 'public_share_pct')
    op.drop_column('popular_parlays', 'true_probability')
    op.drop_column('popular_parlays', 'true_ev_pct')
    op.drop_column('popular_parlays', 'category')
    op.drop_index('ix_user_placed_legs_fixture_result', table_name='user_placed_legs')
    op.drop_index('ix_user_placed_legs_bet', table_name='user_placed_legs')
    op.drop_table('user_placed_legs')
    op.drop_index('ix_user_placed_bets_user_status', table_name='user_placed_bets')
    op.drop_index('ix_user_placed_bets_user_settled', table_name='user_placed_bets')
    op.drop_index('ix_user_placed_bets_user_placed', table_name='user_placed_bets')
    op.drop_table('user_placed_bets')
    op.drop_index('ix_fixture_scores_kickoff', table_name='fixture_scores')
    op.drop_table('fixture_scores')
    # ### end Alembic commands ###
