"""group_44_competitive_intel

Revision ID: c14eae0da3d8
Revises: f208d2dab746
Create Date: 2026-09-30 00:50:17.771310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14eae0da3d8'
down_revision: Union[str, Sequence[str], None] = 'f208d2dab746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_bots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('target_site', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('IDLE', 'SCANNING', 'ERROR')", name=op.f('ck_competitor_bots_ck_competitor_bots_status')),
    sa.CheckConstraint('length(name) > 0', name=op.f('ck_competitor_bots_ck_competitor_bots_name_not_empty')),
    sa.CheckConstraint('length(target_site) > 0', name=op.f('ck_competitor_bots_ck_competitor_bots_target_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_bots')),
    sa.UniqueConstraint('target_site', name=op.f('uq_competitor_bots_target_site'))
    )
    op.create_index('ix_competitor_bots_status', 'competitor_bots', ['status'], unique=False)
    op.create_table('feature_gap_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('missing_feature', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_feature_gap_alerts_ck_feature_gap_alerts_severity')),
    sa.CheckConstraint('length(missing_feature) > 0', name=op.f('ck_feature_gap_alerts_ck_feature_gap_alerts_feature_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_gap_alerts'))
    )
    op.create_index('ix_feature_gap_alerts_resolved_created', 'feature_gap_alerts', ['is_resolved', 'created_at'], unique=False)
    op.create_index('ix_feature_gap_alerts_site_feature', 'feature_gap_alerts', ['site_name', 'missing_feature'], unique=False)
    op.create_table('dev_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gap_id', sa.Uuid(), nullable=False),
    sa.Column('suggestion_text', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(suggestion_text) > 0', name=op.f('ck_dev_suggestions_ck_dev_suggestions_text_not_empty')),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('ck_dev_suggestions_ck_dev_suggestions_priority_range')),
    sa.ForeignKeyConstraint(['gap_id'], ['feature_gap_alerts.id'], name=op.f('fk_dev_suggestions_gap_id_feature_gap_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dev_suggestions'))
    )
    op.create_index('ix_dev_suggestions_gap_priority', 'dev_suggestions', ['gap_id', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dev_suggestions_gap_priority', table_name='dev_suggestions')
    op.drop_table('dev_suggestions')
    op.drop_index('ix_feature_gap_alerts_site_feature', table_name='feature_gap_alerts')
    op.drop_index('ix_feature_gap_alerts_resolved_created', table_name='feature_gap_alerts')
    op.drop_table('feature_gap_alerts')
    op.drop_index('ix_competitor_bots_status', table_name='competitor_bots')
    op.drop_table('competitor_bots')
    # ### end Alembic commands ###
