"""vault fleet credentials accounts reservations config

Revision ID: c4138a07e989
Revises: a79f2b8e4c76
Create Date: 2026-10-10 01:28:15.210928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4138a07e989'
down_revision: Union[str, Sequence[str], None] = 'a79f2b8e4c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_bookmaker_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('identity_digest', sa.String(length=64), nullable=False),
    sa.Column('username_hint', sa.String(length=64), nullable=True),
    sa.Column('encrypted_username', sa.Text(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_token', sa.Text(), nullable=True),
    sa.Column('encrypted_totp_seed', sa.Text(), nullable=True),
    sa.Column('encrypted_notes', sa.Text(), nullable=True),
    sa.Column('encrypted_target_url', sa.Text(), nullable=True),
    sa.Column('target_host', sa.String(length=255), nullable=True),
    sa.Column('secrets_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('adapter_key', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stake_cap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('verification_detail', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'OK', 'FAILED', 'UNSUPPORTED')", name=op.f('ck_vault_bookmaker_accounts_verification_status')),
    sa.CheckConstraint('balance IS NULL OR balance >= 0', name=op.f('ck_vault_bookmaker_accounts_balance_non_negative')),
    sa.CheckConstraint('priority >= 1', name=op.f('ck_vault_bookmaker_accounts_priority_positive')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_vault_bookmaker_accounts_reserved_non_negative')),
    sa.CheckConstraint('stake_cap IS NULL OR stake_cap > 0', name=op.f('ck_vault_bookmaker_accounts_stake_cap_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_bookmaker_accounts')),
    sa.UniqueConstraint('bookmaker_id', 'identity_digest', name='uq_vault_bookmaker_accounts_identity')
    )
    op.create_index('ix_vault_bookmaker_accounts_book_active', 'vault_bookmaker_accounts', ['bookmaker_id', 'is_active'], unique=False)
    op.create_table('vault_fleet_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sports', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('markets_by_sport', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quiet_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('account_routing', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_vault_fleet_config_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_fleet_config'))
    )
    op.create_table('vault_import_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('accounts_created', sa.Integer(), nullable=False),
    sa.Column('accounts_updated', sa.Integer(), nullable=False),
    sa.Column('accounts_unchanged', sa.Integer(), nullable=False),
    sa.Column('providers_created', sa.Integer(), nullable=False),
    sa.Column('providers_updated', sa.Integer(), nullable=False),
    sa.Column('providers_unchanged', sa.Integer(), nullable=False),
    sa.Column('sports_added', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_import_runs'))
    )
    op.create_index(op.f('ix_vault_import_runs_created_at'), 'vault_import_runs', ['created_at'], unique=False)
    op.create_table('vault_provider_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('key_digest', sa.String(length=64), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('api_key_hint', sa.String(length=64), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('linked_source_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('verification_detail', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'OK', 'FAILED', 'UNSUPPORTED')", name=op.f('ck_vault_provider_credentials_verification_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_provider_credentials')),
    sa.UniqueConstraint('provider_id', 'key_digest', name='uq_vault_provider_credentials_key')
    )
    op.create_index(op.f('ix_vault_provider_credentials_provider_id'), 'vault_provider_credentials', ['provider_id'], unique=False)
    op.create_table('vault_account_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('order_ref', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=32), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_vault_account_reservations_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['vault_bookmaker_accounts.id'], name=op.f('fk_vault_account_reservations_account_id_vault_bookmaker_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_account_reservations')),
    sa.UniqueConstraint('order_ref', name=op.f('uq_vault_account_reservations_order_ref'))
    )
    op.create_index('ix_vault_account_reservations_open', 'vault_account_reservations', ['account_id', 'released_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vault_account_reservations_open', table_name='vault_account_reservations')
    op.drop_table('vault_account_reservations')
    op.drop_index(op.f('ix_vault_provider_credentials_provider_id'), table_name='vault_provider_credentials')
    op.drop_table('vault_provider_credentials')
    op.drop_index(op.f('ix_vault_import_runs_created_at'), table_name='vault_import_runs')
    op.drop_table('vault_import_runs')
    op.drop_table('vault_fleet_config')
    op.drop_index('ix_vault_bookmaker_accounts_book_active', table_name='vault_bookmaker_accounts')
    op.drop_table('vault_bookmaker_accounts')
    # ### end Alembic commands ###
