"""group_45_oracle_scout

Revision ID: dd88d1b0c0a9
Revises: c14eae0da3d8
Create Date: 2026-09-30 01:10:32.845289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd88d1b0c0a9'
down_revision: Union[str, Sequence[str], None] = 'c14eae0da3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracle_scout_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('page_context', sa.String(length=120), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('oracle_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(oracle_response) > 0', name=op.f('ck_oracle_scout_history_ck_oracle_scout_history_response_not_empty')),
    sa.CheckConstraint('length(user_message) > 0', name=op.f('ck_oracle_scout_history_ck_oracle_scout_history_message_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oracle_scout_history'))
    )
    op.create_index(op.f('ix_oracle_scout_history_created_at'), 'oracle_scout_history', ['created_at'], unique=False)
    op.create_index('ix_oracle_scout_history_user_created', 'oracle_scout_history', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oracle_scout_history_user_created', table_name='oracle_scout_history')
    op.drop_index(op.f('ix_oracle_scout_history_created_at'), table_name='oracle_scout_history')
    op.drop_table('oracle_scout_history')
    # ### end Alembic commands ###
