"""omni fleet sources and canonical entities

Group 60 ingestion fleet: per-source operator state (toggle, vault-encrypted key, dead-letter
pause) and the canonical entity table the alias dictionary is synced into. Autogenerated from
the models, then given server defaults so rows inserted outside the ORM are valid too.

Revision ID: e2e4d037638c
Revises: a71c0e5d9b22
Create Date: 2026-10-08 12:54:07.448254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e4d037638c'
down_revision: Union[str, Sequence[str], None] = 'a71c0e5d9b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('canonical_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sport_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('team', 'player')", name=op.f('ck_canonical_entities_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_entities')),
    sa.UniqueConstraint('sport_key', 'kind', 'canonical_name', name='uq_canonical_entities_identity')
    )
    op.create_index(op.f('ix_canonical_entities_sport_key'), 'canonical_entities', ['sport_key'], unique=False)
    op.create_table('omni_fleet_sources',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=64), nullable=True),
    sa.Column('interval_seconds', sa.Float(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consecutive_failures >= 0', name=op.f('ck_omni_fleet_sources_failures_non_negative')),
    sa.CheckConstraint('interval_seconds IS NULL OR interval_seconds >= 5', name=op.f('ck_omni_fleet_sources_interval_floor')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_omni_fleet_sources'))
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('omni_fleet_sources')
    op.drop_index(op.f('ix_canonical_entities_sport_key'), table_name='canonical_entities')
    op.drop_table('canonical_entities')
