"""complete news and wire integration (Group 78): The Wire's record

Six tables, all new: wire_venue_locations (venues learnt from ESPN or entered), wire_weather_snapshots (each fixture's
match-window forecast and friction factor), wire_injury_roster_reports (absences, the operator's ratings),
wire_news_sentiment_articles (ingested news, its reading and any catalyst), wire_officiating_records (officiated
matches) and wire_referee_profiles (tendencies per referee and league). Developed for Amit Ashok Kumar Patnaik.

Revision ID: e83f4105a72d
Revises: d71e3092f89c
Create Date: 2026-10-11 01:41:53.850808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e83f4105a72d'
down_revision: Union[str, Sequence[str], None] = 'd71e3092f89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wire_news_sentiment_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source_credibility', sa.Float(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=True),
    sa.Column('teams_mentioned', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('players_mentioned', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fixtures', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('subject', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('tactical_impact', sa.String(length=16), nullable=False),
    sa.Column('baseline_probabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('associated_steam_move_id', sa.String(length=160), nullable=True),
    sa.Column('catalyst', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tactical_impact IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_wire_news_sentiment_articles_impact_known')),
    sa.CheckConstraint('sentiment_score >= -1 AND sentiment_score <= 1', name=op.f('ck_wire_news_sentiment_articles_sentiment_bounded')),
    sa.CheckConstraint('source_credibility >= 0 AND source_credibility <= 1', name=op.f('ck_wire_news_sentiment_articles_credibility_bounded')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wire_news_sentiment_articles')),
    sa.UniqueConstraint('fingerprint', name='uq_wire_news_sentiment_articles_fingerprint')
    )
    op.create_index('ix_wire_news_sentiment_articles_impact_published', 'wire_news_sentiment_articles', ['tactical_impact', 'published_at'], unique=False)
    op.create_index('ix_wire_news_sentiment_articles_published', 'wire_news_sentiment_articles', ['published_at'], unique=False)
    op.create_table('wire_referee_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referee_name', sa.String(length=96), nullable=False),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('matches_officiated', sa.Integer(), nullable=False),
    sa.Column('avg_yellow_cards', sa.Float(), nullable=False),
    sa.Column('avg_red_cards', sa.Float(), nullable=False),
    sa.Column('cards_per_game', sa.Float(), nullable=False),
    sa.Column('penalties_per_90', sa.Float(), nullable=False),
    sa.Column('home_bias_ratio', sa.Float(), nullable=False),
    sa.Column('over_totals_pct', sa.Float(), nullable=False),
    sa.Column('baseline_matches', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wire_referee_profiles')),
    sa.UniqueConstraint('referee_name', 'league', name='uq_wire_referee_profiles_referee_league')
    )
    op.create_table('wire_venue_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('venue_name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('roof_type', sa.String(length=16), nullable=False),
    sa.Column('surface_type', sa.String(length=24), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('espn_venue_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("roof_type IN ('OPEN_AIR', 'RETRACTABLE', 'FIXED_DOME', 'INDOOR')", name=op.f('ck_wire_venue_locations_roof_known')),
    sa.CheckConstraint("surface_type IS NULL OR surface_type IN ('NATURAL_GRASS', 'HYBRID', 'ARTIFICIAL_TURF', 'HARDCOURT', 'CLAY')", name=op.f('ck_wire_venue_locations_surface_known')),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90 AND longitude >= -180 AND longitude <= 180', name=op.f('ck_wire_venue_locations_coordinates_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wire_venue_locations')),
    sa.UniqueConstraint('sport', 'alias', name='uq_wire_venue_locations_sport_alias')
    )
    op.create_table('wire_weather_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('sport_key', sa.String(length=64), nullable=True),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_name', sa.String(length=160), nullable=True),
    sa.Column('venue_source', sa.String(length=64), nullable=True),
    sa.Column('roof_type', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('window_hours', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('wind_cardinal', sa.String(length=4), nullable=True),
    sa.Column('precipitation_mmh', sa.Float(), nullable=True),
    sa.Column('snow', sa.Boolean(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=False),
    sa.Column('pitch_impact_score', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_indoor_dome', sa.Boolean(), nullable=False),
    sa.Column('roof_may_close', sa.Boolean(), nullable=False),
    sa.Column('dew_expected', sa.Boolean(), nullable=False),
    sa.Column('tactical_advisory', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("roof_type IN ('OPEN_AIR', 'RETRACTABLE', 'FIXED_DOME', 'INDOOR')", name=op.f('ck_wire_weather_snapshots_roof_known')),
    sa.CheckConstraint('pitch_impact_score > 0', name=op.f('ck_wire_weather_snapshots_impact_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wire_weather_snapshots'))
    )
    op.create_index('ix_wire_weather_snapshots_fixture_fetched', 'wire_weather_snapshots', ['fixture_id', 'fetched_at'], unique=False)
    op.create_table('wire_injury_roster_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('player_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('injury_nature', sa.String(length=128), nullable=True),
    sa.Column('return_date', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('replacement_quality', sa.Float(), nullable=True),
    sa.Column('rated_by', sa.Uuid(), nullable=True),
    sa.Column('impact_delta_pct', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("side IN ('HOME', 'AWAY')", name=op.f('ck_wire_injury_roster_reports_side_known')),
    sa.CheckConstraint("status IN ('OUT', 'SUSPENDED', 'DOUBTFUL', 'QUESTIONABLE')", name=op.f('ck_wire_injury_roster_reports_status_known')),
    sa.CheckConstraint('rating IS NULL OR rating >= 0', name=op.f('ck_wire_injury_roster_reports_rating_non_negative')),
    sa.CheckConstraint('replacement_quality IS NULL OR (replacement_quality >= 0 AND replacement_quality < 1)', name=op.f('ck_wire_injury_roster_reports_replacement_bounded')),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], name=op.f('fk_wire_injury_roster_reports_rated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wire_injury_roster_reports')),
    sa.UniqueConstraint('fixture_id', 'side', 'player_name', name='uq_wire_injury_roster_reports_fixture_side_player')
    )
    op.create_index(op.f('ix_wire_injury_roster_reports_fixture_id'), 'wire_injury_roster_reports', ['fixture_id'], unique=False)
    op.create_index('ix_wire_injury_roster_reports_player', 'wire_injury_roster_reports', ['sport', 'team_name', 'player_name'], unique=False)
    op.create_table('wire_officiating_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.String(length=128), nullable=True),
    sa.Column('espn_event_id', sa.String(length=32), nullable=True),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.Column('referee_name', sa.String(length=96), nullable=True),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_yellow', sa.Integer(), nullable=True),
    sa.Column('away_yellow', sa.Integer(), nullable=True),
    sa.Column('home_red', sa.Integer(), nullable=True),
    sa.Column('away_red', sa.Integer(), nullable=True),
    sa.Column('home_penalties', sa.Integer(), nullable=True),
    sa.Column('away_penalties', sa.Integer(), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('SCHEDULED', 'FINAL')", name=op.f('ck_wire_officiating_records_status_known')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_wire_officiating_records_assigned_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wire_officiating_records')),
    sa.UniqueConstraint('espn_event_id', name='uq_wire_officiating_records_espn_event_id'),
    sa.UniqueConstraint('fixture_id', name='uq_wire_officiating_records_fixture_id')
    )
    op.create_index('ix_wire_officiating_records_league_referee', 'wire_officiating_records', ['league', 'referee_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wire_officiating_records_league_referee', table_name='wire_officiating_records')
    op.drop_table('wire_officiating_records')
    op.drop_index('ix_wire_injury_roster_reports_player', table_name='wire_injury_roster_reports')
    op.drop_index(op.f('ix_wire_injury_roster_reports_fixture_id'), table_name='wire_injury_roster_reports')
    op.drop_table('wire_injury_roster_reports')
    op.drop_index('ix_wire_weather_snapshots_fixture_fetched', table_name='wire_weather_snapshots')
    op.drop_table('wire_weather_snapshots')
    op.drop_table('wire_venue_locations')
    op.drop_table('wire_referee_profiles')
    op.drop_index('ix_wire_news_sentiment_articles_published', table_name='wire_news_sentiment_articles')
    op.drop_index('ix_wire_news_sentiment_articles_impact_published', table_name='wire_news_sentiment_articles')
    op.drop_table('wire_news_sentiment_articles')
    # ### end Alembic commands ###
