"""group_43_popular_picks

Revision ID: f208d2dab746
Revises: 85734883047b
Create Date: 2026-09-30 00:26:46.202098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f208d2dab746'
down_revision: Union[str, Sequence[str], None] = '85734883047b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_parlays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('pick_type', sa.String(length=32), nullable=False),
    sa.Column('legs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_odds', sa.Float(), nullable=False),
    sa.Column('historical_success_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("pick_type IN ('TRENDING', 'AI_PREDICTED', 'SHARP_MONEY')", name=op.f('ck_popular_parlays_ck_popular_parlays_pick_type')),
    sa.CheckConstraint('historical_success_rate >= 0.0 AND historical_success_rate <= 1.0', name=op.f('ck_popular_parlays_ck_popular_parlays_success_rate_range')),
    sa.CheckConstraint('length(title) > 0', name=op.f('ck_popular_parlays_ck_popular_parlays_title_not_empty')),
    sa.CheckConstraint('total_odds >= 1.0', name=op.f('ck_popular_parlays_ck_popular_parlays_total_odds_min')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_popular_parlays'))
    )
    op.create_index('ix_popular_parlays_active_expires', 'popular_parlays', ['is_active', 'expires_at'], unique=False)
    op.create_index('ix_popular_parlays_expires_at', 'popular_parlays', ['expires_at'], unique=False)
    op.create_index('ix_popular_parlays_legs_gin', 'popular_parlays', ['legs'], unique=False, postgresql_using='gin')
    op.create_index('ix_popular_parlays_pick_type', 'popular_parlays', ['pick_type'], unique=False)
    op.create_table('parlay_review_gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('parlay_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('ACCEPTED', 'REJECTED', 'MODIFIED')", name=op.f('ck_parlay_review_gates_ck_parlay_review_gates_decision')),
    sa.ForeignKeyConstraint(['parlay_id'], ['popular_parlays.id'], name=op.f('fk_parlay_review_gates_parlay_id_popular_parlays'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parlay_review_gates'))
    )
    op.create_index('ix_parlay_review_gates_parlay_created', 'parlay_review_gates', ['parlay_id', 'created_at'], unique=False)
    op.create_index('ix_parlay_review_gates_user_id', 'parlay_review_gates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parlay_review_gates_user_id', table_name='parlay_review_gates')
    op.drop_index('ix_parlay_review_gates_parlay_created', table_name='parlay_review_gates')
    op.drop_table('parlay_review_gates')
    op.drop_index('ix_popular_parlays_pick_type', table_name='popular_parlays')
    op.drop_index('ix_popular_parlays_legs_gin', table_name='popular_parlays', postgresql_using='gin')
    op.drop_index('ix_popular_parlays_expires_at', table_name='popular_parlays')
    op.drop_index('ix_popular_parlays_active_expires', table_name='popular_parlays')
    op.drop_table('popular_parlays')
    # ### end Alembic commands ###
