"""Compatibility re-exports. Structures now live in app.schemas.bet_types."""
from app.schemas.bet_types import (
    MAX_LEGS,
    MAX_SYSTEM_COMBINATIONS,
    MAX_UNIT_STAKE,
    NAMED_SYSTEM_BETS,
    AnyBetStructure,
    BetStructure,
    BetStructureUnion,
    CanadianBet,
    EachWayBet,
    GoliathBet,
    HeinzBet,
    LayBet,
    Lucky15Bet,
    Lucky31Bet,
    Lucky63Bet,
    NamedSystemBet,
    ParlayBet,
    PatentBet,
    SettleRequest,
    SingleBet,
    SuperHeinzBet,
    SystemBet,
    SystemBetBase,
    TrixieBet,
    YankeeBet,
)

__all__ = [
    "MAX_LEGS", "MAX_SYSTEM_COMBINATIONS", "MAX_UNIT_STAKE", "NAMED_SYSTEM_BETS",
    "AnyBetStructure", "BetStructure", "BetStructureUnion", "CanadianBet", "EachWayBet",
    "GoliathBet", "HeinzBet", "LayBet", "Lucky15Bet", "Lucky31Bet", "Lucky63Bet",
    "NamedSystemBet", "ParlayBet", "PatentBet", "SettleRequest", "SingleBet",
    "SuperHeinzBet", "SystemBet", "SystemBetBase", "TrixieBet", "YankeeBet",
]
